// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mrpc-mt5-error.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mt5TermApi {

  /// <summary>Holder for reflection information generated from mrpc-mt5-error.proto</summary>
  public static partial class MrpcMt5ErrorReflection {

    #region Descriptor
    /// <summary>File descriptor for mrpc-mt5-error.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MrpcMt5ErrorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRtcnBjLW10NS1lcnJvci5wcm90bxIMbXQ1X3Rlcm1fYXBpIsIDCgVFcnJv",
            "chIlCgR0eXBlGAEgASgOMhcubXQ1X3Rlcm1fYXBpLkVycm9yVHlwZRISCgpl",
            "cnJvcl9jb2RlGAIgASgJEhUKDWVycm9yX21lc3NhZ2UYAyABKAkSMgoObXFs",
            "X2Vycm9yX2NvZGUYBCABKA4yGi5tdDVfdGVybV9hcGkuTXFsRXJyb3JDb2Rl",
            "EhoKEm1xbF9lcnJvcl9pbnRfY29kZRgFIAEoBRIdChVtcWxfZXJyb3JfZGVz",
            "Y3JpcHRpb24YBiABKAkSPQoUbXFsX2Vycm9yX3RyYWRlX2NvZGUYByABKA4y",
            "Hy5tdDVfdGVybV9hcGkuTXFsRXJyb3JUcmFkZUNvZGUSIAoYbXFsX2Vycm9y",
            "X3RyYWRlX2ludF9jb2RlGAggASgFEiMKG21xbF9lcnJvcl90cmFkZV9kZXNj",
            "cmlwdGlvbhgJIAEoCRITCgtzdGFja190cmFjZRgKIAEoCRIZChFjb21tYW5k",
            "X3R5cGVfbmFtZRgLIAEoCRIRCgljb21tYW5kSWQYDCABKAMSLwoKcHJvcGVy",
            "dGllcxgNIAMoCzIbLm10NV90ZXJtX2FwaS5FcnJvclByb3BlcnR5Ij8KDUVy",
            "cm9yUHJvcGVydHkSFQoNZXJyb3JfYXJnX2tleRgBIAEoCRIXCg9lcnJvcl9h",
            "cmdfdmFsdWUYAiABKAkiaAoLTG9nRmlsZUluZm8SJwoIbG9nX3R5cGUYASAB",
            "KA4yFS5tdDVfdGVybV9hcGkuTG9nVHlwZRIRCglmdWxsX3BhdGgYAiABKAkS",
            "DAoEbmFtZRgDIAEoCRIPCgdjb250ZW50GAQgASgJKoICCglFcnJvclR5cGUS",
            "DQoJVU5ERUZJTkVEEAASCAoETVJQQxABEhMKD01SUENfVkFMSURBVElPThAC",
            "EhAKDE1SUENfVElNRU9VVBADEhgKFFRFUk1JTkFMX0FQSV9USU1FT1VUEAQS",
            "GwoXVEVSTUlOQUxfQVBJX0dFVF9QQVJBTVMQBRIbChdURVJNSU5BTF9BUElf",
            "U0VUX1JFU1VMVBAGEhsKF1RFUk1JTkFMX0FQSV9VTkVYUEVDVEVEEAcSEQoN",
            "TVFMX0VYRUNVVElPThAIEhgKFE1RTF9DVVNUT01fRVhFQ1VUSU9OEAkSFwoT",
            "TVFMX1RSQURFX0VYRUNVVElPThAKKikKB0xvZ1R5cGUSCgoGR2xvYmFsEAAS",
            "CAoETVFMNRABEggKBE1RTDQQAirjMQoMTXFsRXJyb3JDb2RlEg8KC0VSUl9T",
            "VUNDRVNTEAASFwoSRVJSX0lOVEVSTkFMX0VSUk9SEKEfEiEKHEVSUl9XUk9O",
            "R19JTlRFUk5BTF9QQVJBTUVURVIQoh8SGgoVRVJSX0lOVkFMSURfUEFSQU1F",
            "VEVSEKMfEhoKFUVSUl9OT1RfRU5PVUdIX01FTU9SWRCkHxIjCh5FUlJfU1RS",
            "VUNUX1dJVEhPQkpFQ1RTX09SQ0xBU1MQpR8SFgoRRVJSX0lOVkFMSURfQVJS",
            "QVkQph8SGwoWRVJSX0FSUkFZX1JFU0laRV9FUlJPUhCnHxIcChdFUlJfU1RS",
            "SU5HX1JFU0laRV9FUlJPUhCoHxIeChlFUlJfTk9USU5JVElBTElaRURfU1RS",
            "SU5HEKkfEhkKFEVSUl9JTlZBTElEX0RBVEVUSU1FEKofEhcKEkVSUl9BUlJB",
            "WV9CQURfU0laRRCrHxIYChNFUlJfSU5WQUxJRF9QT0lOVEVSEKwfEh0KGEVS",
            "Ul9JTlZBTElEX1BPSU5URVJfVFlQRRCtHxIdChhFUlJfRlVOQ1RJT05fTk9U",
            "X0FMTE9XRUQQrh8SIQocRVJSX1JFU09VUkNFX05BTUVfRFVQTElDQVRFRBCv",
            "HxIbChZFUlJfUkVTT1VSQ0VfTk9UX0ZPVU5EELAfEiIKHUVSUl9SRVNPVVJD",
            "RV9VTlNVUFBPUlRFRF9UWVBFELEfEiIKHUVSUl9SRVNPVVJDRV9OQU1FX0lT",
            "X1RPT19MT05HELIfEhYKEUVSUl9NQVRIX09WRVJGTE9XELMfEhQKD0VSUl9T",
            "TEVFUF9FUlJPUhC0HxIYChNFUlJfUFJPR1JBTV9TVE9QUEVEELYfEhUKEEVS",
            "Ul9JTlZBTElEX1RZUEUQtx8SFwoSRVJSX0lOVkFMSURfSEFORExFELgfEhkK",
            "FEVSUl9UT09fTUFOWV9PQkpFQ1RTELkfEhcKEkVSUl9DSEFSVF9XUk9OR19J",
            "RBCFIBIXChJFUlJfQ0hBUlRfTk9fUkVQTFkQhiASGAoTRVJSX0NIQVJUX05P",
            "VF9GT1VORBCHIBIYChNFUlJfQ0hBUlRfTk9fRVhQRVJUEIggEhoKFUVSUl9D",
            "SEFSVF9DQU5OT1RfT1BFThCJIBIcChdFUlJfQ0hBUlRfQ0FOTk9UX0NIQU5H",
            "RRCKIBIeChlFUlJfQ0hBUlRfV1JPTkdfUEFSQU1FVEVSEIsgEiIKHUVSUl9D",
            "SEFSVF9DQU5OT1RfQ1JFQVRFX1RJTUVSEIwgEh0KGEVSUl9DSEFSVF9XUk9O",
            "R19QUk9QRVJUWRCNIBIgChtFUlJfQ0hBUlRfU0NSRUVOU0hPVF9GQUlMRUQQ",
            "jiASHgoZRVJSX0NIQVJUX05BVklHQVRFX0ZBSUxFRBCPIBIeChlFUlJfQ0hB",
            "UlRfVEVNUExBVEVfRkFJTEVEEJAgEh8KGkVSUl9DSEFSVF9XSU5ET1dfTk9U",
            "X0ZPVU5EEJEgEiMKHkVSUl9DSEFSVF9JTkRJQ0FUT1JfQ0FOTk9UX0FERBCS",
            "IBIjCh5FUlJfQ0hBUlRfSU5ESUNBVE9SX0NBTk5PVF9ERUwQkyASIgodRVJS",
            "X0NIQVJUX0lORElDQVRPUl9OT1RfRk9VTkQQlCASFQoQRVJSX09CSkVDVF9F",
            "UlJPUhDpIBIZChRFUlJfT0JKRUNUX05PVF9GT1VORBDqIBIeChlFUlJfT0JK",
            "RUNUX1dST05HX1BST1BFUlRZEOsgEh4KGUVSUl9PQkpFQ1RfR0VUREFURV9G",
            "QUlMRUQQ7CASHwoaRVJSX09CSkVDVF9HRVRWQUxVRV9GQUlMRUQQ7SASHgoZ",
            "RVJSX01BUktFVF9VTktOT1dOX1NZTUJPTBDNIRIcChdFUlJfTUFSS0VUX05P",
            "VF9TRUxFQ1RFRBDOIRIeChlFUlJfTUFSS0VUX1dST05HX1BST1BFUlRZEM8h",
            "EiAKG0VSUl9NQVJLRVRfTEFTVFRJTUVfVU5LTk9XThDQIRIcChdFUlJfTUFS",
            "S0VUX1NFTEVDVF9FUlJPUhDRIRIcChdFUlJfTUFSS0VUX1NFTEVDVF9MSU1J",
            "VBDSIRIdChhFUlJfTUFSS0VUX1NFU1NJT05fSU5ERVgQ0yESGgoVRVJSX0hJ",
            "U1RPUllfTk9UX0ZPVU5EELEiEh8KGkVSUl9ISVNUT1JZX1dST05HX1BST1BF",
            "UlRZELIiEhgKE0VSUl9ISVNUT1JZX1RJTUVPVVQQsyISGwoWRVJSX0hJU1RP",
            "UllfQkFSU19MSU1JVBC0IhIcChdFUlJfSElTVE9SWV9MT0FEX0VSUk9SUxC1",
            "IhIdChhFUlJfSElTVE9SWV9TTUFMTF9CVUZGRVIQtyISIQocRVJSX0dMT0JB",
            "TFZBUklBQkxFX05PVF9GT1VORBCVIxIeChlFUlJfR0xPQkFMVkFSSUFCTEVf",
            "RVhJU1RTEJYjEiQKH0VSUl9HTE9CQUxWQVJJQUJMRV9OT1RfTU9ESUZJRUQQ",
            "lyMSIgodRVJSX0dMT0JBTFZBUklBQkxFX0NBTk5PVFJFQUQQmCMSIwoeRVJS",
            "X0dMT0JBTFZBUklBQkxFX0NBTk5PVFdSSVRFEJkjEhkKFEVSUl9NQUlMX1NF",
            "TkRfRkFJTEVEEJ4jEhoKFUVSUl9QTEFZX1NPVU5EX0ZBSUxFRBCfIxIcChdF",
            "UlJfTVFMNV9XUk9OR19QUk9QRVJUWRCgIxIgChtFUlJfVEVSTUlOQUxfV1JP",
            "TkdfUFJPUEVSVFkQoSMSGAoTRVJSX0ZUUF9TRU5EX0ZBSUxFRBCiIxIhChxF",
            "UlJfTk9USUZJQ0FUSU9OX1NFTkRfRkFJTEVEEKMjEiUKIEVSUl9OT1RJRklD",
            "QVRJT05fV1JPTkdfUEFSQU1FVEVSEKQjEiQKH0VSUl9OT1RJRklDQVRJT05f",
            "V1JPTkdfU0VUVElOR1MQpSMSIgodRVJSX05PVElGSUNBVElPTl9UT09fRlJF",
            "UVVFTlQQpiMSFQoQRVJSX0ZUUF9OT1NFUlZFUhCnIxIUCg9FUlJfRlRQX05P",
            "TE9HSU4QqCMSFwoSRVJSX0ZUUF9GSUxFX0VSUk9SEKkjEhsKFkVSUl9GVFBf",
            "Q09OTkVDVF9GQUlMRUQQqiMSFgoRRVJSX0ZUUF9DSEFOR0VESVIQqyMSGgoV",
            "RVJSX0JVRkZFUlNfTk9fTUVNT1JZEPkjEhwKF0VSUl9CVUZGRVJTX1dST05H",
            "X0lOREVYEPojEh4KGUVSUl9DVVNUT01fV1JPTkdfUFJPUEVSVFkQ+yMSHwoa",
            "RVJSX0FDQ09VTlRfV1JPTkdfUFJPUEVSVFkQ3SQSHQoYRVJSX1RSQURFX1dS",
            "T05HX1BST1BFUlRZEI8lEhcKEkVSUl9UUkFERV9ESVNBQkxFRBCQJRIhChxF",
            "UlJfVFJBREVfUE9TSVRJT05fTk9UX0ZPVU5EEJElEh4KGUVSUl9UUkFERV9P",
            "UkRFUl9OT1RfRk9VTkQQkiUSHQoYRVJSX1RSQURFX0RFQUxfTk9UX0ZPVU5E",
            "EJMlEhoKFUVSUl9UUkFERV9TRU5EX0ZBSUxFRBCUJRIaChVFUlJfVFJBREVf",
            "Q0FMQ19GQUlMRUQQliUSIQocRVJSX0lORElDQVRPUl9VTktOT1dOX1NZTUJP",
            "TBDBJRIgChtFUlJfSU5ESUNBVE9SX0NBTk5PVF9DUkVBVEUQwiUSHAoXRVJS",
            "X0lORElDQVRPUl9OT19NRU1PUlkQwyUSHwoaRVJSX0lORElDQVRPUl9DQU5O",
            "T1RfQVBQTFkQxCUSHQoYRVJSX0lORElDQVRPUl9DQU5OT1RfQUREEMUlEiEK",
            "HEVSUl9JTkRJQ0FUT1JfREFUQV9OT1RfRk9VTkQQxiUSHwoaRVJSX0lORElD",
            "QVRPUl9XUk9OR19IQU5ETEUQxyUSIwoeRVJSX0lORElDQVRPUl9XUk9OR19Q",
            "QVJBTUVURVJTEMglEhkKFEVSUl9CT09LU19DQU5OT1RfQUREEKUmEhwKF0VS",
            "Ul9CT09LU19DQU5OT1RfREVMRVRFEKYmEhkKFEVSUl9CT09LU19DQU5OT1Rf",
            "R0VUEKcmEh8KGkVSUl9CT09LU19DQU5OT1RfU1VCU0NSSUJFEKgmEhcKEkVS",
            "Ul9UT09fTUFOWV9GSUxFUxCJJxIXChJFUlJfV1JPTkdfRklMRU5BTUUQiicS",
            "GgoVRVJSX1RPT19MT05HX0ZJTEVOQU1FEIsnEhkKFEVSUl9DQU5OT1RfT1BF",
            "Tl9GSUxFEIwnEh8KGkVSUl9GSUxFX0NBQ0hFQlVGRkVSX0VSUk9SEI0nEhsK",
            "FkVSUl9DQU5OT1RfREVMRVRFX0ZJTEUQjicSGwoWRVJSX0lOVkFMSURfRklM",
            "RUhBTkRMRRCPJxIZChRFUlJfV1JPTkdfRklMRUhBTkRMRRCQJxIXChJFUlJf",
            "Tk9fU1RSSU5HX0RBVEUQpicSGgoVRVJSX1dST05HX1NUUklOR19EQVRFEKcn",
            "EhoKFUVSUl9XUk9OR19TVFJJTkdfVElNRRCoJxIaChVFUlJfU1RSSU5HX1RJ",
            "TUVfRVJST1IQqScSHQoYRVJSX1NUUklOR19PVVRfT0ZfTUVNT1JZEKonEhwK",
            "F0VSUl9JTkNPTVBBVElCTEVfQVJSQVlTELonEh0KGEVSUl9TTUFMTF9BU1NF",
            "UklFU19BUlJBWRC7JxIUCg9FUlJfU01BTExfQVJSQVkQvCcSFwoSRVJSX1pF",
            "Uk9TSVpFX0FSUkFZEL0nEhsKFkVSUl9OVU1CRVJfQVJSQVlTX09OTFkQvicS",
            "HQoYRVJSX09QRU5DTF9OT1RfU1VQUE9SVEVEEOwnEhgKE0VSUl9PUEVOQ0xf",
            "SU5URVJOQUwQ7ScSHgoZRVJSX09QRU5DTF9JTlZBTElEX0hBTkRMRRDuJxIe",
            "ChlFUlJfT1BFTkNMX0NPTlRFWFRfQ1JFQVRFEO8nEhwKF0VSUl9PUEVOQ0xf",
            "UVVFVUVfQ1JFQVRFEPAnEh4KGUVSUl9PUEVOQ0xfUFJPR1JBTV9DUkVBVEUQ",
            "8ScSJAofRVJSX09QRU5DTF9UT09fTE9OR19LRVJORUxfTkFNRRDyJxIdChhF",
            "UlJfT1BFTkNMX0tFUk5FTF9DUkVBVEUQ8ycSJAofRVJSX09QRU5DTF9TRVRf",
            "S0VSTkVMX1BBUkFNRVRFUhD0JxIXChJFUlJfT1BFTkNMX0VYRUNVVEUQ9ScS",
            "IQocRVJSX09QRU5DTF9XUk9OR19CVUZGRVJfU0laRRD2JxIjCh5FUlJfT1BF",
            "TkNMX1dST05HX0JVRkZFUl9PRkZTRVQQ9ycSHQoYRVJSX09QRU5DTF9CVUZG",
            "RVJfQ1JFQVRFEPgnEiAKG0VSUl9PUEVOQ0xfVE9PX01BTllfT0JKRUNUUxD5",
            "JxIcChdFUlJfT1BFTkNMX1NFTEVDVERFVklDRRD6JxIaChVFUlJfREFUQUJB",
            "U0VfSU5URVJOQUwQgCgSIAobRVJSX0RBVEFCQVNFX0lOVkFMSURfSEFORExF",
            "EIEoEiIKHUVSUl9EQVRBQkFTRV9UT09fTUFOWV9PQkpFQ1RTEIIoEhkKFEVS",
            "Ul9EQVRBQkFTRV9DT05ORUNUEIMoEhkKFEVSUl9EQVRBQkFTRV9FWEVDVVRF",
            "EIQoEhkKFEVSUl9EQVRBQkFTRV9QUkVQQVJFEIUoEh4KGUVSUl9EQVRBQkFT",
            "RV9OT19NT1JFX0RBVEEQhigSFgoRRVJSX0RBVEFCQVNFX1NURVAQhygSGwoW",
            "RVJSX0RBVEFCQVNFX05PVF9SRUFEWRCIKBIhChxFUlJfREFUQUJBU0VfQklO",
            "RF9QQVJBTUVURVJTEIkoEiMKHkVSUl9XRUJSRVFVRVNUX0lOVkFMSURfQURE",
            "UkVTUxDQKBIiCh1FUlJfV0VCUkVRVUVTVF9DT05ORUNUX0ZBSUxFRBDRKBIb",
            "ChZFUlJfV0VCUkVRVUVTVF9USU1FT1VUENIoEiIKHUVSUl9XRUJSRVFVRVNU",
            "X1JFUVVFU1RfRkFJTEVEENMoEiAKG0VSUl9ORVRTT0NLRVRfSU5WQUxJREhB",
            "TkRMRRCWKRIiCh1FUlJfTkVUU09DS0VUX1RPT19NQU5ZX09QRU5FRBCXKRIh",
            "ChxFUlJfTkVUU09DS0VUX0NBTk5PVF9DT05ORUNUEJgpEhsKFkVSUl9ORVRT",
            "T0NLRVRfSU9fRVJST1IQmSkSIwoeRVJSX05FVFNPQ0tFVF9IQU5EU0hBS0Vf",
            "RkFJTEVEEJopEiEKHEVSUl9ORVRTT0NLRVRfTk9fQ0VSVElGSUNBVEUQmykS",
            "GgoVRVJSX05PVF9DVVNUT01fU1lNQk9MELQpEiEKHEVSUl9DVVNUT01fU1lN",
            "Qk9MX1dST05HX05BTUUQtSkSIAobRVJSX0NVU1RPTV9TWU1CT0xfTkFNRV9M",
            "T05HELYpEiAKG0VSUl9DVVNUT01fU1lNQk9MX1BBVEhfTE9ORxC3KRIcChdF",
            "UlJfQ1VTVE9NX1NZTUJPTF9FWElTVBC4KRIcChdFUlJfQ1VTVE9NX1NZTUJP",
            "TF9FUlJPUhC5KRIfChpFUlJfQ1VTVE9NX1NZTUJPTF9TRUxFQ1RFRBC6KRIl",
            "CiBFUlJfQ1VTVE9NX1NZTUJPTF9QUk9QRVJUWV9XUk9ORxC7KRImCiFFUlJf",
            "Q1VTVE9NX1NZTUJPTF9QQVJBTUVURVJfRVJST1IQvCkSJQogRVJSX0NVU1RP",
            "TV9TWU1CT0xfUEFSQU1FVEVSX0xPTkcQvSkSIQocRVJSX0NVU1RPTV9USUNL",
            "U19XUk9OR19PUkRFUhC+KRIbChZFUlJfQ0FMRU5EQVJfTU9SRV9EQVRBEJgq",
            "EhkKFEVSUl9DQUxFTkRBUl9USU1FT1VUEJkqEhkKFEVSUl9DQUxFTkRBUl9O",
            "T19EQVRBEJoqEhcKEkVSUl9EQVRBQkFTRV9FUlJPUhDhKxIXChJFUlJfREFU",
            "QUJBU0VfTE9HSUMQ4isSFgoRRVJSX0RBVEFCQVNFX1BFUk0Q4ysSFwoSRVJS",
            "X0RBVEFCQVNFX0FCT1JUEOQrEhYKEUVSUl9EQVRBQkFTRV9CVVNZEOUrEhgK",
            "E0VSUl9EQVRBQkFTRV9MT0NLRUQQ5isSFwoSRVJSX0RBVEFCQVNFX05PTUVN",
            "EOcrEhoKFUVSUl9EQVRBQkFTRV9SRUFET05MWRDoKxIbChZFUlJfREFUQUJB",
            "U0VfSU5URVJSVVBUEOkrEhcKEkVSUl9EQVRBQkFTRV9JT0VSUhDqKxIZChRF",
            "UlJfREFUQUJBU0VfQ09SUlVQVBDrKxIaChVFUlJfREFUQUJBU0VfTk9URk9V",
            "TkQQ7CsSFgoRRVJSX0RBVEFCQVNFX0ZVTEwQ7SsSGgoVRVJSX0RBVEFCQVNF",
            "X0NBTlRPUEVOEO4rEhoKFUVSUl9EQVRBQkFTRV9QUk9UT0NPTBDvKxIXChJF",
            "UlJfREFUQUJBU0VfRU1QVFkQ8CsSGAoTRVJSX0RBVEFCQVNFX1NDSEVNQRDx",
            "KxIYChNFUlJfREFUQUJBU0VfVE9PQklHEPIrEhwKF0VSUl9EQVRBQkFTRV9D",
            "T05TVFJBSU5UEPMrEhoKFUVSUl9EQVRBQkFTRV9NSVNNQVRDSBD0KxIYChNF",
            "UlJfREFUQUJBU0VfTUlTVVNFEPUrEhcKEkVSUl9EQVRBQkFTRV9OT0xGUxD2",
            "KxIWChFFUlJfREFUQUJBU0VfQVVUSBD3KxIYChNFUlJfREFUQUJBU0VfRk9S",
            "TUFUEPgrEhcKEkVSUl9EQVRBQkFTRV9SQU5HRRD5KxIYChNFUlJfREFUQUJB",
            "U0VfTk9UQURCEPorEhgKE0VSUl9NQVRSSVhfSU5URVJOQUwQxCwSHwoaRVJS",
            "X01BVFJJWF9OT1RfSU5JVElBTElaRUQQxSwSHAoXRVJSX01BVFJJWF9JTkNP",
            "TlNJU1RFTlQQxiwSHAoXRVJSX01BVFJJWF9JTlZBTElEX1NJWkUQxywSHAoX",
            "RVJSX01BVFJJWF9JTlZBTElEX1RZUEUQyCwSIAobRVJSX01BVFJJWF9GVU5D",
            "X05PVF9BTExPV0VEEMksEhwKF0VSUl9NQVRSSVhfQ09OVEFJTlNfTkFOEMos",
            "EhYKEUVSUl9PTk5YX0lOVEVSTkFMEKgtEh0KGEVSUl9PTk5YX05PVF9JTklU",
            "SUFMSVpFRBCpLRIbChZFUlJfT05OWF9OT1RfU1VQUE9SVEVEEKotEhgKE0VS",
            "Ul9PTk5YX1JVTl9GQUlMRUQQqy0SJgohRVJSX09OTlhfSU5WQUxJRF9QQVJB",
            "TUVURVJTX0NPVU5UEKwtEh8KGkVSUl9PTk5YX0lOVkFMSURfUEFSQU1FVEVS",
            "EK0tEiQKH0VSUl9PTk5YX0lOVkFMSURfUEFSQU1FVEVSX1RZUEUQri0SJAof",
            "RVJSX09OTlhfSU5WQUxJRF9QQVJBTUVURVJfU0laRRCvLRIdChhFUlJfT05O",
            "WF9XUk9OR19ESU1FTlNJT04QsC0SGgoURVJSX1VTRVJfRVJST1JfRklSU1QQ",
            "gIAEKt0KChFNcWxFcnJvclRyYWRlQ29kZRIZChVUUkFERV9SRVRDT0RFX1NV",
            "Q0NFU1MQABIaChVUUkFERV9SRVRDT0RFX1JFUVVPVEUQlE4SGQoUVFJBREVf",
            "UkVUQ09ERV9SRUpFQ1QQlk4SGQoUVFJBREVfUkVUQ09ERV9DQU5DRUwQl04S",
            "GQoUVFJBREVfUkVUQ09ERV9QTEFDRUQQmE4SFwoSVFJBREVfUkVUQ09ERV9E",
            "T05FEJlOEh8KGlRSQURFX1JFVENPREVfRE9ORV9QQVJUSUFMEJpOEhgKE1RS",
            "QURFX1JFVENPREVfRVJST1IQm04SGgoVVFJBREVfUkVUQ09ERV9USU1FT1VU",
            "EJxOEhoKFVRSQURFX1JFVENPREVfSU5WQUxJRBCdThIhChxUUkFERV9SRVRD",
            "T0RFX0lOVkFMSURfVk9MVU1FEJ5OEiAKG1RSQURFX1JFVENPREVfSU5WQUxJ",
            "RF9QUklDRRCfThIgChtUUkFERV9SRVRDT0RFX0lOVkFMSURfU1RPUFMQoE4S",
            "IQocVFJBREVfUkVUQ09ERV9UUkFERV9ESVNBQkxFRBChThIgChtUUkFERV9S",
            "RVRDT0RFX01BUktFVF9DTE9TRUQQok4SGwoWVFJBREVfUkVUQ09ERV9OT19N",
            "T05FWRCjThIgChtUUkFERV9SRVRDT0RFX1BSSUNFX0NIQU5HRUQQpE4SHAoX",
            "VFJBREVfUkVUQ09ERV9QUklDRV9PRkYQpU4SJQogVFJBREVfUkVUQ09ERV9J",
            "TlZBTElEX0VYUElSQVRJT04Qpk4SIAobVFJBREVfUkVUQ09ERV9PUkRFUl9D",
            "SEFOR0VEEKdOEiQKH1RSQURFX1JFVENPREVfVE9PX01BTllfUkVRVUVTVFMQ",
            "qE4SHQoYVFJBREVfUkVUQ09ERV9OT19DSEFOR0VTEKlOEiUKIFRSQURFX1JF",
            "VENPREVfU0VSVkVSX0RJU0FCTEVTX0FUEKpOEiUKIFRSQURFX1JFVENPREVf",
            "Q0xJRU5UX0RJU0FCTEVTX0FUEKtOEhkKFFRSQURFX1JFVENPREVfTE9DS0VE",
            "EKxOEhkKFFRSQURFX1JFVENPREVfRlJPWkVOEK1OEh8KGlRSQURFX1JFVENP",
            "REVfSU5WQUxJRF9GSUxMEK5OEh0KGFRSQURFX1JFVENPREVfQ09OTkVDVElP",
            "ThCvThIcChdUUkFERV9SRVRDT0RFX09OTFlfUkVBTBCwThIfChpUUkFERV9S",
            "RVRDT0RFX0xJTUlUX09SREVSUxCxThIfChpUUkFERV9SRVRDT0RFX0xJTUlU",
            "X1ZPTFVNRRCyThIgChtUUkFERV9SRVRDT0RFX0lOVkFMSURfT1JERVIQs04S",
            "IgodVFJBREVfUkVUQ09ERV9QT1NJVElPTl9DTE9TRUQQtE4SJwoiVFJBREVf",
            "UkVUQ09ERV9JTlZBTElEX0NMT1NFX1ZPTFVNRRC2ThIkCh9UUkFERV9SRVRD",
            "T0RFX0NMT1NFX09SREVSX0VYSVNUELdOEiIKHVRSQURFX1JFVENPREVfTElN",
            "SVRfUE9TSVRJT05TELhOEiAKG1RSQURFX1JFVENPREVfUkVKRUNUX0NBTkNF",
            "TBC5ThIcChdUUkFERV9SRVRDT0RFX0xPTkdfT05MWRC6ThIdChhUUkFERV9S",
            "RVRDT0RFX1NIT1JUX09OTFkQu04SHQoYVFJBREVfUkVUQ09ERV9DTE9TRV9P",
            "TkxZELxOEh0KGFRSQURFX1JFVENPREVfRklGT19DTE9TRRC9ThIjCh5UUkFE",
            "RV9SRVRDT0RFX0hFREdFX1BST0hJQklURUQQvk5CM1oxZ2l0Lm10YXBpLmlv",
            "L3Jvb3QvbXJwYy1wcm90by5naXQvbXQ1L2xpYnJhcmllcy9nb2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Mt5TermApi.ErrorType), typeof(global::Mt5TermApi.LogType), typeof(global::Mt5TermApi.MqlErrorCode), typeof(global::Mt5TermApi.MqlErrorTradeCode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mt5TermApi.Error), global::Mt5TermApi.Error.Parser, new[]{ "Type", "ErrorCode", "ErrorMessage", "MqlErrorCode", "MqlErrorIntCode", "MqlErrorDescription", "MqlErrorTradeCode", "MqlErrorTradeIntCode", "MqlErrorTradeDescription", "StackTrace", "CommandTypeName", "CommandId", "Properties" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mt5TermApi.ErrorProperty), global::Mt5TermApi.ErrorProperty.Parser, new[]{ "ErrorArgKey", "ErrorArgValue" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mt5TermApi.LogFileInfo), global::Mt5TermApi.LogFileInfo.Parser, new[]{ "LogType", "FullPath", "Name", "Content" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ErrorType {
    [pbr::OriginalName("UNDEFINED")] Undefined = 0,
    [pbr::OriginalName("MRPC")] Mrpc = 1,
    [pbr::OriginalName("MRPC_VALIDATION")] MrpcValidation = 2,
    [pbr::OriginalName("MRPC_TIMEOUT")] MrpcTimeout = 3,
    [pbr::OriginalName("TERMINAL_API_TIMEOUT")] TerminalApiTimeout = 4,
    [pbr::OriginalName("TERMINAL_API_GET_PARAMS")] TerminalApiGetParams = 5,
    [pbr::OriginalName("TERMINAL_API_SET_RESULT")] TerminalApiSetResult = 6,
    [pbr::OriginalName("TERMINAL_API_UNEXPECTED")] TerminalApiUnexpected = 7,
    [pbr::OriginalName("MQL_EXECUTION")] MqlExecution = 8,
    [pbr::OriginalName("MQL_CUSTOM_EXECUTION")] MqlCustomExecution = 9,
    [pbr::OriginalName("MQL_TRADE_EXECUTION")] MqlTradeExecution = 10,
  }

  public enum LogType {
    [pbr::OriginalName("Global")] Global = 0,
    [pbr::OriginalName("MQL5")] Mql5 = 1,
    [pbr::OriginalName("MQL4")] Mql4 = 2,
  }

  public enum MqlErrorCode {
    /// <summary>
    /// The operation completed successfully
    /// </summary>
    [pbr::OriginalName("ERR_SUCCESS")] ErrSuccess = 0,
    /// <summary>
    /// Unexpected internal error
    /// </summary>
    [pbr::OriginalName("ERR_INTERNAL_ERROR")] ErrInternalError = 4001,
    /// <summary>
    /// Wrong parameter in the inner call of the client terminal function
    /// </summary>
    [pbr::OriginalName("ERR_WRONG_INTERNAL_PARAMETER")] ErrWrongInternalParameter = 4002,
    /// <summary>
    /// Wrong parameter when calling the system function
    /// </summary>
    [pbr::OriginalName("ERR_INVALID_PARAMETER")] ErrInvalidParameter = 4003,
    /// <summary>
    /// Not enough memory to perform the system function
    /// </summary>
    [pbr::OriginalName("ERR_NOT_ENOUGH_MEMORY")] ErrNotEnoughMemory = 4004,
    /// <summary>
    /// The structure contains objects of strings and/or dynamic arrays and/or structure of such objects and/or classes
    /// </summary>
    [pbr::OriginalName("ERR_STRUCT_WITHOBJECTS_ORCLASS")] ErrStructWithobjectsOrclass = 4005,
    /// <summary>
    /// Array of a wrong type, wrong size, or a damaged object of a dynamic array
    /// </summary>
    [pbr::OriginalName("ERR_INVALID_ARRAY")] ErrInvalidArray = 4006,
    /// <summary>
    /// Not enough memory for the relocation of an array, or an attempt to change the size of a static array
    /// </summary>
    [pbr::OriginalName("ERR_ARRAY_RESIZE_ERROR")] ErrArrayResizeError = 4007,
    /// <summary>
    /// Not enough memory for the relocation of string
    /// </summary>
    [pbr::OriginalName("ERR_STRING_RESIZE_ERROR")] ErrStringResizeError = 4008,
    /// <summary>
    /// Not initialized string
    /// </summary>
    [pbr::OriginalName("ERR_NOTINITIALIZED_STRING")] ErrNotinitializedString = 4009,
    /// <summary>
    /// Invalid date and/or time
    /// </summary>
    [pbr::OriginalName("ERR_INVALID_DATETIME")] ErrInvalidDatetime = 4010,
    /// <summary>
    /// Total amount of elements in the array cannot exceed 2147483647
    /// </summary>
    [pbr::OriginalName("ERR_ARRAY_BAD_SIZE")] ErrArrayBadSize = 4011,
    /// <summary>
    /// Wrong pointer
    /// </summary>
    [pbr::OriginalName("ERR_INVALID_POINTER")] ErrInvalidPointer = 4012,
    /// <summary>
    /// Wrong type of pointer
    /// </summary>
    [pbr::OriginalName("ERR_INVALID_POINTER_TYPE")] ErrInvalidPointerType = 4013,
    /// <summary>
    /// Function is not allowed for call
    /// </summary>
    [pbr::OriginalName("ERR_FUNCTION_NOT_ALLOWED")] ErrFunctionNotAllowed = 4014,
    /// <summary>
    /// The names of the dynamic and the static resource match
    /// </summary>
    [pbr::OriginalName("ERR_RESOURCE_NAME_DUPLICATED")] ErrResourceNameDuplicated = 4015,
    /// <summary>
    /// Resource with this name has not been found in EX5
    /// </summary>
    [pbr::OriginalName("ERR_RESOURCE_NOT_FOUND")] ErrResourceNotFound = 4016,
    /// <summary>
    /// Unsupported resource type or its size exceeds 16 Mb
    /// </summary>
    [pbr::OriginalName("ERR_RESOURCE_UNSUPPORTED_TYPE")] ErrResourceUnsupportedType = 4017,
    /// <summary>
    /// The resource name exceeds 63 characters
    /// </summary>
    [pbr::OriginalName("ERR_RESOURCE_NAME_IS_TOO_LONG")] ErrResourceNameIsTooLong = 4018,
    /// <summary>
    /// Overflow occurred when calculating math function
    /// </summary>
    [pbr::OriginalName("ERR_MATH_OVERFLOW")] ErrMathOverflow = 4019,
    /// <summary>
    /// Out of test end date after calling Sleep()
    /// </summary>
    [pbr::OriginalName("ERR_SLEEP_ERROR")] ErrSleepError = 4020,
    /// <summary>
    /// Test forcibly stopped from the outside
    /// </summary>
    [pbr::OriginalName("ERR_PROGRAM_STOPPED")] ErrProgramStopped = 4022,
    /// <summary>
    /// Invalid type
    /// </summary>
    [pbr::OriginalName("ERR_INVALID_TYPE")] ErrInvalidType = 4023,
    /// <summary>
    /// Invalid handle
    /// </summary>
    [pbr::OriginalName("ERR_INVALID_HANDLE")] ErrInvalidHandle = 4024,
    /// <summary>
    /// Object pool filled out
    /// </summary>
    [pbr::OriginalName("ERR_TOO_MANY_OBJECTS")] ErrTooManyObjects = 4025,
    /// <summary>
    /// Charts
    /// </summary>
    [pbr::OriginalName("ERR_CHART_WRONG_ID")] ErrChartWrongId = 4101,
    /// <summary>
    /// Chart does not respond
    /// </summary>
    [pbr::OriginalName("ERR_CHART_NO_REPLY")] ErrChartNoReply = 4102,
    /// <summary>
    /// Chart not found
    /// </summary>
    [pbr::OriginalName("ERR_CHART_NOT_FOUND")] ErrChartNotFound = 4103,
    /// <summary>
    /// No Expert Advisor in the chart that could handle the event
    /// </summary>
    [pbr::OriginalName("ERR_CHART_NO_EXPERT")] ErrChartNoExpert = 4104,
    /// <summary>
    /// Chart opening error
    /// </summary>
    [pbr::OriginalName("ERR_CHART_CANNOT_OPEN")] ErrChartCannotOpen = 4105,
    /// <summary>
    /// Failed to change chart symbol and period
    /// </summary>
    [pbr::OriginalName("ERR_CHART_CANNOT_CHANGE")] ErrChartCannotChange = 4106,
    /// <summary>
    /// Error value of the parameter for the function of working with charts
    /// </summary>
    [pbr::OriginalName("ERR_CHART_WRONG_PARAMETER")] ErrChartWrongParameter = 4107,
    /// <summary>
    /// Failed to create timer
    /// </summary>
    [pbr::OriginalName("ERR_CHART_CANNOT_CREATE_TIMER")] ErrChartCannotCreateTimer = 4108,
    /// <summary>
    /// Wrong chart property ID
    /// </summary>
    [pbr::OriginalName("ERR_CHART_WRONG_PROPERTY")] ErrChartWrongProperty = 4109,
    /// <summary>
    /// Error creating screenshots
    /// </summary>
    [pbr::OriginalName("ERR_CHART_SCREENSHOT_FAILED")] ErrChartScreenshotFailed = 4110,
    /// <summary>
    /// Error navigating through chart
    /// </summary>
    [pbr::OriginalName("ERR_CHART_NAVIGATE_FAILED")] ErrChartNavigateFailed = 4111,
    /// <summary>
    /// Error applying template
    /// </summary>
    [pbr::OriginalName("ERR_CHART_TEMPLATE_FAILED")] ErrChartTemplateFailed = 4112,
    /// <summary>
    /// Subwindow containing the indicator was not found
    /// </summary>
    [pbr::OriginalName("ERR_CHART_WINDOW_NOT_FOUND")] ErrChartWindowNotFound = 4113,
    /// <summary>
    /// Error adding an indicator to chart
    /// </summary>
    [pbr::OriginalName("ERR_CHART_INDICATOR_CANNOT_ADD")] ErrChartIndicatorCannotAdd = 4114,
    /// <summary>
    /// Error deleting an indicator from the chart
    /// </summary>
    [pbr::OriginalName("ERR_CHART_INDICATOR_CANNOT_DEL")] ErrChartIndicatorCannotDel = 4115,
    /// <summary>
    /// Indicator not found on the specified chart
    /// </summary>
    [pbr::OriginalName("ERR_CHART_INDICATOR_NOT_FOUND")] ErrChartIndicatorNotFound = 4116,
    /// <summary>
    /// Graphical Objects
    /// </summary>
    [pbr::OriginalName("ERR_OBJECT_ERROR")] ErrObjectError = 4201,
    /// <summary>
    /// Graphical object was not found
    /// </summary>
    [pbr::OriginalName("ERR_OBJECT_NOT_FOUND")] ErrObjectNotFound = 4202,
    /// <summary>
    /// Wrong ID of a graphical object property
    /// </summary>
    [pbr::OriginalName("ERR_OBJECT_WRONG_PROPERTY")] ErrObjectWrongProperty = 4203,
    /// <summary>
    /// Unable to get date corresponding to the value
    /// </summary>
    [pbr::OriginalName("ERR_OBJECT_GETDATE_FAILED")] ErrObjectGetdateFailed = 4204,
    /// <summary>
    /// Unable to get value corresponding to the date
    /// </summary>
    [pbr::OriginalName("ERR_OBJECT_GETVALUE_FAILED")] ErrObjectGetvalueFailed = 4205,
    /// <summary>
    /// MarketInfo
    /// </summary>
    [pbr::OriginalName("ERR_MARKET_UNKNOWN_SYMBOL")] ErrMarketUnknownSymbol = 4301,
    /// <summary>
    /// Symbol is not selected in MarketWatch
    /// </summary>
    [pbr::OriginalName("ERR_MARKET_NOT_SELECTED")] ErrMarketNotSelected = 4302,
    /// <summary>
    /// Wrong identifier of a symbol property
    /// </summary>
    [pbr::OriginalName("ERR_MARKET_WRONG_PROPERTY")] ErrMarketWrongProperty = 4303,
    /// <summary>
    /// Time of the last tick is not known (no ticks)
    /// </summary>
    [pbr::OriginalName("ERR_MARKET_LASTTIME_UNKNOWN")] ErrMarketLasttimeUnknown = 4304,
    /// <summary>
    /// Error adding or deleting a symbol in MarketWatch
    /// </summary>
    [pbr::OriginalName("ERR_MARKET_SELECT_ERROR")] ErrMarketSelectError = 4305,
    /// <summary>
    /// Exceeded the limit of selected symbols in MarketWatch
    /// </summary>
    [pbr::OriginalName("ERR_MARKET_SELECT_LIMIT")] ErrMarketSelectLimit = 4306,
    /// <summary>
    /// Wrong session ID when calling the SymbolInfoSessionQuote/SymbolInfoSessionTrade function
    /// </summary>
    [pbr::OriginalName("ERR_MARKET_SESSION_INDEX")] ErrMarketSessionIndex = 4307,
    /// <summary>
    /// History Access Errors
    /// </summary>
    [pbr::OriginalName("ERR_HISTORY_NOT_FOUND")] ErrHistoryNotFound = 4401,
    /// <summary>
    /// Wrong ID of the history property
    /// </summary>
    [pbr::OriginalName("ERR_HISTORY_WRONG_PROPERTY")] ErrHistoryWrongProperty = 4402,
    /// <summary>
    /// Exceeded history request timeout
    /// </summary>
    [pbr::OriginalName("ERR_HISTORY_TIMEOUT")] ErrHistoryTimeout = 4403,
    /// <summary>
    /// Number of requested bars limited by terminal settings
    /// </summary>
    [pbr::OriginalName("ERR_HISTORY_BARS_LIMIT")] ErrHistoryBarsLimit = 4404,
    /// <summary>
    /// Multiple errors when loading history
    /// </summary>
    [pbr::OriginalName("ERR_HISTORY_LOAD_ERRORS")] ErrHistoryLoadErrors = 4405,
    /// <summary>
    /// Receiving array is too small to store all requested data
    /// </summary>
    [pbr::OriginalName("ERR_HISTORY_SMALL_BUFFER")] ErrHistorySmallBuffer = 4407,
    /// <summary>
    /// Global Variables Errors
    /// </summary>
    [pbr::OriginalName("ERR_GLOBALVARIABLE_NOT_FOUND")] ErrGlobalvariableNotFound = 4501,
    /// <summary>
    /// Global variable already exists
    /// </summary>
    [pbr::OriginalName("ERR_GLOBALVARIABLE_EXISTS")] ErrGlobalvariableExists = 4502,
    /// <summary>
    /// Global variables were not modified
    /// </summary>
    [pbr::OriginalName("ERR_GLOBALVARIABLE_NOT_MODIFIED")] ErrGlobalvariableNotModified = 4503,
    /// <summary>
    /// Cannot read file with global variable values
    /// </summary>
    [pbr::OriginalName("ERR_GLOBALVARIABLE_CANNOTREAD")] ErrGlobalvariableCannotread = 4504,
    /// <summary>
    /// Cannot write file with global variable values
    /// </summary>
    [pbr::OriginalName("ERR_GLOBALVARIABLE_CANNOTWRITE")] ErrGlobalvariableCannotwrite = 4505,
    /// <summary>
    /// Email sending failed
    /// </summary>
    [pbr::OriginalName("ERR_MAIL_SEND_FAILED")] ErrMailSendFailed = 4510,
    /// <summary>
    /// Sound playing failed
    /// </summary>
    [pbr::OriginalName("ERR_PLAY_SOUND_FAILED")] ErrPlaySoundFailed = 4511,
    /// <summary>
    /// Wrong identifier of the program property
    /// </summary>
    [pbr::OriginalName("ERR_MQL5_WRONG_PROPERTY")] ErrMql5WrongProperty = 4512,
    /// <summary>
    /// Wrong identifier of the terminal property
    /// </summary>
    [pbr::OriginalName("ERR_TERMINAL_WRONG_PROPERTY")] ErrTerminalWrongProperty = 4513,
    /// <summary>
    /// File sending via FTP failed
    /// </summary>
    [pbr::OriginalName("ERR_FTP_SEND_FAILED")] ErrFtpSendFailed = 4514,
    /// <summary>
    /// Failed to send a notification
    /// </summary>
    [pbr::OriginalName("ERR_NOTIFICATION_SEND_FAILED")] ErrNotificationSendFailed = 4515,
    /// <summary>
    /// Invalid parameter for notification
    /// </summary>
    [pbr::OriginalName("ERR_NOTIFICATION_WRONG_PARAMETER")] ErrNotificationWrongParameter = 4516,
    /// <summary>
    /// Wrong notification settings
    /// </summary>
    [pbr::OriginalName("ERR_NOTIFICATION_WRONG_SETTINGS")] ErrNotificationWrongSettings = 4517,
    /// <summary>
    /// Too frequent notifications
    /// </summary>
    [pbr::OriginalName("ERR_NOTIFICATION_TOO_FREQUENT")] ErrNotificationTooFrequent = 4518,
    /// <summary>
    /// FTP server not specified
    /// </summary>
    [pbr::OriginalName("ERR_FTP_NOSERVER")] ErrFtpNoserver = 4519,
    /// <summary>
    /// FTP login not specified
    /// </summary>
    [pbr::OriginalName("ERR_FTP_NOLOGIN")] ErrFtpNologin = 4520,
    /// <summary>
    /// File not found for FTP upload
    /// </summary>
    [pbr::OriginalName("ERR_FTP_FILE_ERROR")] ErrFtpFileError = 4521,
    /// <summary>
    /// FTP connection failed
    /// </summary>
    [pbr::OriginalName("ERR_FTP_CONNECT_FAILED")] ErrFtpConnectFailed = 4522,
    /// <summary>
    /// FTP path not found on server
    /// </summary>
    [pbr::OriginalName("ERR_FTP_CHANGEDIR")] ErrFtpChangedir = 4523,
    /// <summary>
    /// Custom Indicator Buffers Errors
    /// </summary>
    [pbr::OriginalName("ERR_BUFFERS_NO_MEMORY")] ErrBuffersNoMemory = 4601,
    /// <summary>
    /// Wrong indicator buffer index
    /// </summary>
    [pbr::OriginalName("ERR_BUFFERS_WRONG_INDEX")] ErrBuffersWrongIndex = 4602,
    /// <summary>
    /// Custom Indicator Properties Errors
    /// </summary>
    [pbr::OriginalName("ERR_CUSTOM_WRONG_PROPERTY")] ErrCustomWrongProperty = 4603,
    /// <summary>
    /// Account Errors
    /// </summary>
    [pbr::OriginalName("ERR_ACCOUNT_WRONG_PROPERTY")] ErrAccountWrongProperty = 4701,
    /// <summary>
    /// Wrong trade property ID
    /// </summary>
    [pbr::OriginalName("ERR_TRADE_WRONG_PROPERTY")] ErrTradeWrongProperty = 4751,
    /// <summary>
    /// Trading by Expert Advisors prohibited
    /// </summary>
    [pbr::OriginalName("ERR_TRADE_DISABLED")] ErrTradeDisabled = 4752,
    /// <summary>
    /// Position not found
    /// </summary>
    [pbr::OriginalName("ERR_TRADE_POSITION_NOT_FOUND")] ErrTradePositionNotFound = 4753,
    /// <summary>
    /// Order not found
    /// </summary>
    [pbr::OriginalName("ERR_TRADE_ORDER_NOT_FOUND")] ErrTradeOrderNotFound = 4754,
    /// <summary>
    /// Deal not found
    /// </summary>
    [pbr::OriginalName("ERR_TRADE_DEAL_NOT_FOUND")] ErrTradeDealNotFound = 4755,
    /// <summary>
    /// Trade request sending failed
    /// </summary>
    [pbr::OriginalName("ERR_TRADE_SEND_FAILED")] ErrTradeSendFailed = 4756,
    /// <summary>
    /// Failed to calculate profit or margin
    /// </summary>
    [pbr::OriginalName("ERR_TRADE_CALC_FAILED")] ErrTradeCalcFailed = 4758,
    /// <summary>
    /// Indicator Errors
    /// </summary>
    [pbr::OriginalName("ERR_INDICATOR_UNKNOWN_SYMBOL")] ErrIndicatorUnknownSymbol = 4801,
    /// <summary>
    /// Indicator cannot be created
    /// </summary>
    [pbr::OriginalName("ERR_INDICATOR_CANNOT_CREATE")] ErrIndicatorCannotCreate = 4802,
    /// <summary>
    /// Not enough memory for the indicator
    /// </summary>
    [pbr::OriginalName("ERR_INDICATOR_NO_MEMORY")] ErrIndicatorNoMemory = 4803,
    /// <summary>
    /// Cannot apply indicator to another indicator
    /// </summary>
    [pbr::OriginalName("ERR_INDICATOR_CANNOT_APPLY")] ErrIndicatorCannotApply = 4804,
    /// <summary>
    /// Error applying indicator to chart
    /// </summary>
    [pbr::OriginalName("ERR_INDICATOR_CANNOT_ADD")] ErrIndicatorCannotAdd = 4805,
    /// <summary>
    /// Requested data not found
    /// </summary>
    [pbr::OriginalName("ERR_INDICATOR_DATA_NOT_FOUND")] ErrIndicatorDataNotFound = 4806,
    /// <summary>
    /// Wrong indicator handle
    /// </summary>
    [pbr::OriginalName("ERR_INDICATOR_WRONG_HANDLE")] ErrIndicatorWrongHandle = 4807,
    /// <summary>
    /// Wrong parameters when creating indicator
    /// </summary>
    [pbr::OriginalName("ERR_INDICATOR_WRONG_PARAMETERS")] ErrIndicatorWrongParameters = 4808,
    /// <summary>
    /// Depth of Market Errors
    /// </summary>
    [pbr::OriginalName("ERR_BOOKS_CANNOT_ADD")] ErrBooksCannotAdd = 4901,
    /// <summary>
    /// Depth Of Market cannot be removed
    /// </summary>
    [pbr::OriginalName("ERR_BOOKS_CANNOT_DELETE")] ErrBooksCannotDelete = 4902,
    /// <summary>
    /// Cannot obtain Depth Of Market data
    /// </summary>
    [pbr::OriginalName("ERR_BOOKS_CANNOT_GET")] ErrBooksCannotGet = 4903,
    /// <summary>
    /// Subscription error for Depth Of Market
    /// </summary>
    [pbr::OriginalName("ERR_BOOKS_CANNOT_SUBSCRIBE")] ErrBooksCannotSubscribe = 4904,
    /// <summary>
    /// File Operations Errors
    /// </summary>
    [pbr::OriginalName("ERR_TOO_MANY_FILES")] ErrTooManyFiles = 5001,
    /// <summary>
    /// Invalid file name
    /// </summary>
    [pbr::OriginalName("ERR_WRONG_FILENAME")] ErrWrongFilename = 5002,
    /// <summary>
    /// File name too long
    /// </summary>
    [pbr::OriginalName("ERR_TOO_LONG_FILENAME")] ErrTooLongFilename = 5003,
    /// <summary>
    /// File opening error
    /// </summary>
    [pbr::OriginalName("ERR_CANNOT_OPEN_FILE")] ErrCannotOpenFile = 5004,
    /// <summary>
    /// Not enough memory for cache
    /// </summary>
    [pbr::OriginalName("ERR_FILE_CACHEBUFFER_ERROR")] ErrFileCachebufferError = 5005,
    /// <summary>
    /// File deleting error
    /// </summary>
    [pbr::OriginalName("ERR_CANNOT_DELETE_FILE")] ErrCannotDeleteFile = 5006,
    /// <summary>
    /// Invalid file handle
    /// </summary>
    [pbr::OriginalName("ERR_INVALID_FILEHANDLE")] ErrInvalidFilehandle = 5007,
    /// <summary>
    /// Wrong file handle
    /// </summary>
    [pbr::OriginalName("ERR_WRONG_FILEHANDLE")] ErrWrongFilehandle = 5008,
    /// <summary>
    /// String Casting Errors
    /// </summary>
    [pbr::OriginalName("ERR_NO_STRING_DATE")] ErrNoStringDate = 5030,
    /// <summary>
    /// Wrong date in string
    /// </summary>
    [pbr::OriginalName("ERR_WRONG_STRING_DATE")] ErrWrongStringDate = 5031,
    /// <summary>
    /// Wrong time in string
    /// </summary>
    [pbr::OriginalName("ERR_WRONG_STRING_TIME")] ErrWrongStringTime = 5032,
    /// <summary>
    /// Error converting string to date
    /// </summary>
    [pbr::OriginalName("ERR_STRING_TIME_ERROR")] ErrStringTimeError = 5033,
    /// <summary>
    /// Not enough memory for string
    /// </summary>
    [pbr::OriginalName("ERR_STRING_OUT_OF_MEMORY")] ErrStringOutOfMemory = 5034,
    /// <summary>
    /// Operations with Arrays
    /// </summary>
    [pbr::OriginalName("ERR_INCOMPATIBLE_ARRAYS")] ErrIncompatibleArrays = 5050,
    /// <summary>
    /// Insufficient size of AS_SERIES array
    /// </summary>
    [pbr::OriginalName("ERR_SMALL_ASSERIES_ARRAY")] ErrSmallAsseriesArray = 5051,
    /// <summary>
    /// Array too small
    /// </summary>
    [pbr::OriginalName("ERR_SMALL_ARRAY")] ErrSmallArray = 5052,
    /// <summary>
    /// Zero-length array
    /// </summary>
    [pbr::OriginalName("ERR_ZEROSIZE_ARRAY")] ErrZerosizeArray = 5053,
    /// <summary>
    /// Must be a numeric array
    /// </summary>
    [pbr::OriginalName("ERR_NUMBER_ARRAYS_ONLY")] ErrNumberArraysOnly = 5054,
    /// <summary>
    /// OpenCL Errors
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_NOT_SUPPORTED")] ErrOpenclNotSupported = 5100,
    /// <summary>
    /// Internal OpenCL error
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_INTERNAL")] ErrOpenclInternal = 5101,
    /// <summary>
    /// Invalid OpenCL handle
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_INVALID_HANDLE")] ErrOpenclInvalidHandle = 5102,
    /// <summary>
    /// Error creating OpenCL context
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_CONTEXT_CREATE")] ErrOpenclContextCreate = 5103,
    /// <summary>
    /// Error creating OpenCL run queue
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_QUEUE_CREATE")] ErrOpenclQueueCreate = 5104,
    /// <summary>
    /// OpenCL program compilation error
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_PROGRAM_CREATE")] ErrOpenclProgramCreate = 5105,
    /// <summary>
    /// Kernel name too long
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_TOO_LONG_KERNEL_NAME")] ErrOpenclTooLongKernelName = 5106,
    /// <summary>
    /// OpenCL kernel creation error
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_KERNEL_CREATE")] ErrOpenclKernelCreate = 5107,
    /// <summary>
    /// Error occurred when setting parameters for the OpenCL kernel
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_SET_KERNEL_PARAMETER")] ErrOpenclSetKernelParameter = 5108,
    /// <summary>
    /// OpenCL program runtime error
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_EXECUTE")] ErrOpenclExecute = 5109,
    /// <summary>
    /// Invalid size of the OpenCL buffer
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_WRONG_BUFFER_SIZE")] ErrOpenclWrongBufferSize = 5110,
    /// <summary>
    /// Invalid offset in the OpenCL buffer
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_WRONG_BUFFER_OFFSET")] ErrOpenclWrongBufferOffset = 5111,
    /// <summary>
    /// Failed to create an OpenCL buffer
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_BUFFER_CREATE")] ErrOpenclBufferCreate = 5112,
    /// <summary>
    /// Too many OpenCL objects
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_TOO_MANY_OBJECTS")] ErrOpenclTooManyObjects = 5113,
    /// <summary>
    /// OpenCL device selection error
    /// </summary>
    [pbr::OriginalName("ERR_OPENCL_SELECTDEVICE")] ErrOpenclSelectdevice = 5114,
    /// <summary>
    /// Database Errors
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_INTERNAL")] ErrDatabaseInternal = 5120,
    /// <summary>
    /// Invalid database handle
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_INVALID_HANDLE")] ErrDatabaseInvalidHandle = 5121,
    /// <summary>
    /// Exceeded the maximum acceptable number of Database objects
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_TOO_MANY_OBJECTS")] ErrDatabaseTooManyObjects = 5122,
    /// <summary>
    /// Database connection error
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_CONNECT")] ErrDatabaseConnect = 5123,
    /// <summary>
    /// Request execution error
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_EXECUTE")] ErrDatabaseExecute = 5124,
    /// <summary>
    /// Request generation error
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_PREPARE")] ErrDatabasePrepare = 5125,
    /// <summary>
    /// No more data to read
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_NO_MORE_DATA")] ErrDatabaseNoMoreData = 5126,
    /// <summary>
    /// Failed to move to the next request entry
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_STEP")] ErrDatabaseStep = 5127,
    /// <summary>
    /// Data for reading request results are not ready yet
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_NOT_READY")] ErrDatabaseNotReady = 5128,
    /// <summary>
    /// Failed to auto substitute parameters to an SQL request
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_BIND_PARAMETERS")] ErrDatabaseBindParameters = 5129,
    /// <summary>
    /// WebRequest Errors
    /// </summary>
    [pbr::OriginalName("ERR_WEBREQUEST_INVALID_ADDRESS")] ErrWebrequestInvalidAddress = 5200,
    /// <summary>
    /// Failed to connect to specified URL
    /// </summary>
    [pbr::OriginalName("ERR_WEBREQUEST_CONNECT_FAILED")] ErrWebrequestConnectFailed = 5201,
    /// <summary>
    /// Timeout exceeded
    /// </summary>
    [pbr::OriginalName("ERR_WEBREQUEST_TIMEOUT")] ErrWebrequestTimeout = 5202,
    /// <summary>
    /// HTTP request failed
    /// </summary>
    [pbr::OriginalName("ERR_WEBREQUEST_REQUEST_FAILED")] ErrWebrequestRequestFailed = 5203,
    /// <summary>
    /// Network (Sockets) Errors
    /// </summary>
    [pbr::OriginalName("ERR_NETSOCKET_INVALIDHANDLE")] ErrNetsocketInvalidhandle = 5270,
    /// <summary>
    /// Too many open sockets (max 128)
    /// </summary>
    [pbr::OriginalName("ERR_NETSOCKET_TOO_MANY_OPENED")] ErrNetsocketTooManyOpened = 5271,
    /// <summary>
    /// Failed to connect to remote host
    /// </summary>
    [pbr::OriginalName("ERR_NETSOCKET_CANNOT_CONNECT")] ErrNetsocketCannotConnect = 5272,
    /// <summary>
    /// Failed to send/receive data from socket
    /// </summary>
    [pbr::OriginalName("ERR_NETSOCKET_IO_ERROR")] ErrNetsocketIoError = 5273,
    /// <summary>
    /// Failed to establish secure connection (TLS Handshake)
    /// </summary>
    [pbr::OriginalName("ERR_NETSOCKET_HANDSHAKE_FAILED")] ErrNetsocketHandshakeFailed = 5274,
    /// <summary>
    /// No data on certificate protecting the connection
    /// </summary>
    [pbr::OriginalName("ERR_NETSOCKET_NO_CERTIFICATE")] ErrNetsocketNoCertificate = 5275,
    /// <summary>
    /// Custom Symbols Errors
    /// </summary>
    [pbr::OriginalName("ERR_NOT_CUSTOM_SYMBOL")] ErrNotCustomSymbol = 5300,
    /// <summary>
    /// Invalid custom symbol name
    /// </summary>
    [pbr::OriginalName("ERR_CUSTOM_SYMBOL_WRONG_NAME")] ErrCustomSymbolWrongName = 5301,
    /// <summary>
    /// Custom symbol name too long
    /// </summary>
    [pbr::OriginalName("ERR_CUSTOM_SYMBOL_NAME_LONG")] ErrCustomSymbolNameLong = 5302,
    /// <summary>
    /// Custom symbol path too long
    /// </summary>
    [pbr::OriginalName("ERR_CUSTOM_SYMBOL_PATH_LONG")] ErrCustomSymbolPathLong = 5303,
    /// <summary>
    /// Custom symbol with the same name already exists
    /// </summary>
    [pbr::OriginalName("ERR_CUSTOM_SYMBOL_EXIST")] ErrCustomSymbolExist = 5304,
    /// <summary>
    /// Error creating, deleting, or modifying the custom symbol
    /// </summary>
    [pbr::OriginalName("ERR_CUSTOM_SYMBOL_ERROR")] ErrCustomSymbolError = 5305,
    /// <summary>
    /// Cannot delete a selected custom symbol in Market Watch
    /// </summary>
    [pbr::OriginalName("ERR_CUSTOM_SYMBOL_SELECTED")] ErrCustomSymbolSelected = 5306,
    /// <summary>
    /// Invalid custom symbol property
    /// </summary>
    [pbr::OriginalName("ERR_CUSTOM_SYMBOL_PROPERTY_WRONG")] ErrCustomSymbolPropertyWrong = 5307,
    /// <summary>
    /// Incorrect parameter for setting a custom symbol property
    /// </summary>
    [pbr::OriginalName("ERR_CUSTOM_SYMBOL_PARAMETER_ERROR")] ErrCustomSymbolParameterError = 5308,
    /// <summary>
    /// Too long parameter string for setting a custom symbol property
    /// </summary>
    [pbr::OriginalName("ERR_CUSTOM_SYMBOL_PARAMETER_LONG")] ErrCustomSymbolParameterLong = 5309,
    /// <summary>
    /// Ticks in the array are not arranged in the order of time
    /// </summary>
    [pbr::OriginalName("ERR_CUSTOM_TICKS_WRONG_ORDER")] ErrCustomTicksWrongOrder = 5310,
    /// <summary>
    /// Economic Calendar Errors
    /// </summary>
    [pbr::OriginalName("ERR_CALENDAR_MORE_DATA")] ErrCalendarMoreData = 5400,
    /// <summary>
    /// Request time limit exceeded
    /// </summary>
    [pbr::OriginalName("ERR_CALENDAR_TIMEOUT")] ErrCalendarTimeout = 5401,
    /// <summary>
    /// Country not found
    /// </summary>
    [pbr::OriginalName("ERR_CALENDAR_NO_DATA")] ErrCalendarNoData = 5402,
    /// <summary>
    /// Additional Database Errors
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_ERROR")] ErrDatabaseError = 5601,
    /// <summary>
    /// SQLite internal logic error
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_LOGIC")] ErrDatabaseLogic = 5602,
    /// <summary>
    /// Access denied
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_PERM")] ErrDatabasePerm = 5603,
    /// <summary>
    /// Callback routine requested abort
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_ABORT")] ErrDatabaseAbort = 5604,
    /// <summary>
    /// Database file locked
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_BUSY")] ErrDatabaseBusy = 5605,
    /// <summary>
    /// Database table locked
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_LOCKED")] ErrDatabaseLocked = 5606,
    /// <summary>
    /// Insufficient memory for completing operation
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_NOMEM")] ErrDatabaseNomem = 5607,
    /// <summary>
    /// Attempt to write to readonly database
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_READONLY")] ErrDatabaseReadonly = 5608,
    /// <summary>
    /// Operation terminated by sqlite3_interrupt()
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_INTERRUPT")] ErrDatabaseInterrupt = 5609,
    /// <summary>
    /// Disk I/O error
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_IOERR")] ErrDatabaseIoerr = 5610,
    /// <summary>
    /// Database disk image corrupted
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_CORRUPT")] ErrDatabaseCorrupt = 5611,
    /// <summary>
    /// Unknown operation code in sqlite3_file_control()
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_NOTFOUND")] ErrDatabaseNotfound = 5612,
    /// <summary>
    /// Insertion failed because database is full
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_FULL")] ErrDatabaseFull = 5613,
    /// <summary>
    /// Unable to open the database file
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_CANTOPEN")] ErrDatabaseCantopen = 5614,
    /// <summary>
    /// Database lock protocol error
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_PROTOCOL")] ErrDatabaseProtocol = 5615,
    /// <summary>
    /// Internal use only
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_EMPTY")] ErrDatabaseEmpty = 5616,
    /// <summary>
    /// Database schema changed
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_SCHEMA")] ErrDatabaseSchema = 5617,
    /// <summary>
    /// String or BLOB exceeds size limit
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_TOOBIG")] ErrDatabaseToobig = 5618,
    /// <summary>
    /// Abort due to constraint violation
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_CONSTRAINT")] ErrDatabaseConstraint = 5619,
    /// <summary>
    /// Data type mismatch
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_MISMATCH")] ErrDatabaseMismatch = 5620,
    /// <summary>
    /// Library used incorrectly
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_MISUSE")] ErrDatabaseMisuse = 5621,
    /// <summary>
    /// Uses OS features not supported on host
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_NOLFS")] ErrDatabaseNolfs = 5622,
    /// <summary>
    /// Authorization denied
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_AUTH")] ErrDatabaseAuth = 5623,
    /// <summary>
    /// Not used
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_FORMAT")] ErrDatabaseFormat = 5624,
    /// <summary>
    /// Bind parameter error, incorrect index
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_RANGE")] ErrDatabaseRange = 5625,
    /// <summary>
    /// File opened that is not a database file
    /// </summary>
    [pbr::OriginalName("ERR_DATABASE_NOTADB")] ErrDatabaseNotadb = 5626,
    /// <summary>
    /// Matrix and Vector Methods Errors
    /// </summary>
    [pbr::OriginalName("ERR_MATRIX_INTERNAL")] ErrMatrixInternal = 5700,
    /// <summary>
    /// Matrix/vector not initialized
    /// </summary>
    [pbr::OriginalName("ERR_MATRIX_NOT_INITIALIZED")] ErrMatrixNotInitialized = 5701,
    /// <summary>
    /// Inconsistent size of matrices/vectors in operation
    /// </summary>
    [pbr::OriginalName("ERR_MATRIX_INCONSISTENT")] ErrMatrixInconsistent = 5702,
    /// <summary>
    /// Invalid matrix/vector size
    /// </summary>
    [pbr::OriginalName("ERR_MATRIX_INVALID_SIZE")] ErrMatrixInvalidSize = 5703,
    /// <summary>
    /// Invalid matrix/vector type
    /// </summary>
    [pbr::OriginalName("ERR_MATRIX_INVALID_TYPE")] ErrMatrixInvalidType = 5704,
    /// <summary>
    /// Function not available for this matrix/vector
    /// </summary>
    [pbr::OriginalName("ERR_MATRIX_FUNC_NOT_ALLOWED")] ErrMatrixFuncNotAllowed = 5705,
    /// <summary>
    /// Matrix/vector contains non-numbers (NaN/Inf)
    /// </summary>
    [pbr::OriginalName("ERR_MATRIX_CONTAINS_NAN")] ErrMatrixContainsNan = 5706,
    /// <summary>
    /// ONNX Model Errors
    /// </summary>
    [pbr::OriginalName("ERR_ONNX_INTERNAL")] ErrOnnxInternal = 5800,
    /// <summary>
    /// ONNX Runtime API initialization error
    /// </summary>
    [pbr::OriginalName("ERR_ONNX_NOT_INITIALIZED")] ErrOnnxNotInitialized = 5801,
    /// <summary>
    /// Property or value not supported by MQL5
    /// </summary>
    [pbr::OriginalName("ERR_ONNX_NOT_SUPPORTED")] ErrOnnxNotSupported = 5802,
    /// <summary>
    /// ONNX runtime API run error
    /// </summary>
    [pbr::OriginalName("ERR_ONNX_RUN_FAILED")] ErrOnnxRunFailed = 5803,
    /// <summary>
    /// Invalid number of parameters passed to OnnxRun
    /// </summary>
    [pbr::OriginalName("ERR_ONNX_INVALID_PARAMETERS_COUNT")] ErrOnnxInvalidParametersCount = 5804,
    /// <summary>
    /// Invalid parameter value
    /// </summary>
    [pbr::OriginalName("ERR_ONNX_INVALID_PARAMETER")] ErrOnnxInvalidParameter = 5805,
    /// <summary>
    /// Invalid parameter type
    /// </summary>
    [pbr::OriginalName("ERR_ONNX_INVALID_PARAMETER_TYPE")] ErrOnnxInvalidParameterType = 5806,
    /// <summary>
    /// Invalid parameter size
    /// </summary>
    [pbr::OriginalName("ERR_ONNX_INVALID_PARAMETER_SIZE")] ErrOnnxInvalidParameterSize = 5807,
    /// <summary>
    /// Tensor dimension not set or invalid
    /// </summary>
    [pbr::OriginalName("ERR_ONNX_WRONG_DIMENSION")] ErrOnnxWrongDimension = 5808,
    /// <summary>
    /// User Errors
    /// </summary>
    [pbr::OriginalName("ERR_USER_ERROR_FIRST")] ErrUserErrorFirst = 65536,
  }

  public enum MqlErrorTradeCode {
    [pbr::OriginalName("TRADE_RETCODE_SUCCESS")] TradeRetcodeSuccess = 0,
    /// <summary>
    /// Requote
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_REQUOTE")] TradeRetcodeRequote = 10004,
    /// <summary>
    /// Request rejected
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_REJECT")] TradeRetcodeReject = 10006,
    /// <summary>
    /// Request canceled by trader
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_CANCEL")] TradeRetcodeCancel = 10007,
    /// <summary>
    /// Order placed
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_PLACED")] TradeRetcodePlaced = 10008,
    /// <summary>
    /// Request completed
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_DONE")] TradeRetcodeDone = 10009,
    /// <summary>
    /// Only part of the request was completed
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_DONE_PARTIAL")] TradeRetcodeDonePartial = 10010,
    /// <summary>
    /// Request processing error
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_ERROR")] TradeRetcodeError = 10011,
    /// <summary>
    /// Request canceled by timeout
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_TIMEOUT")] TradeRetcodeTimeout = 10012,
    /// <summary>
    /// Invalid request
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_INVALID")] TradeRetcodeInvalid = 10013,
    /// <summary>
    /// Invalid volume in the request
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_INVALID_VOLUME")] TradeRetcodeInvalidVolume = 10014,
    /// <summary>
    /// Invalid price in the request
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_INVALID_PRICE")] TradeRetcodeInvalidPrice = 10015,
    /// <summary>
    /// Invalid stops in the request
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_INVALID_STOPS")] TradeRetcodeInvalidStops = 10016,
    /// <summary>
    /// Trade is disabled
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_TRADE_DISABLED")] TradeRetcodeTradeDisabled = 10017,
    /// <summary>
    /// Market is closed
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_MARKET_CLOSED")] TradeRetcodeMarketClosed = 10018,
    /// <summary>
    /// Not enough money to complete the request
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_NO_MONEY")] TradeRetcodeNoMoney = 10019,
    /// <summary>
    /// Prices changed
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_PRICE_CHANGED")] TradeRetcodePriceChanged = 10020,
    /// <summary>
    /// No quotes to process the request
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_PRICE_OFF")] TradeRetcodePriceOff = 10021,
    /// <summary>
    /// Invalid order expiration date
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_INVALID_EXPIRATION")] TradeRetcodeInvalidExpiration = 10022,
    /// <summary>
    /// Order state changed
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_ORDER_CHANGED")] TradeRetcodeOrderChanged = 10023,
    /// <summary>
    /// Too frequent requests
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_TOO_MANY_REQUESTS")] TradeRetcodeTooManyRequests = 10024,
    /// <summary>
    /// No changes in request
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_NO_CHANGES")] TradeRetcodeNoChanges = 10025,
    /// <summary>
    /// Autotrading disabled by server
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_SERVER_DISABLES_AT")] TradeRetcodeServerDisablesAt = 10026,
    /// <summary>
    /// Autotrading disabled by client terminal
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_CLIENT_DISABLES_AT")] TradeRetcodeClientDisablesAt = 10027,
    /// <summary>
    /// Request locked for processing
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_LOCKED")] TradeRetcodeLocked = 10028,
    /// <summary>
    /// Order or position frozen
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_FROZEN")] TradeRetcodeFrozen = 10029,
    /// <summary>
    /// Invalid order filling type
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_INVALID_FILL")] TradeRetcodeInvalidFill = 10030,
    /// <summary>
    /// No connection with trade server
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_CONNECTION")] TradeRetcodeConnection = 10031,
    /// <summary>
    /// Operation allowed only for live accounts
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_ONLY_REAL")] TradeRetcodeOnlyReal = 10032,
    /// <summary>
    /// Limit of pending orders reached
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_LIMIT_ORDERS")] TradeRetcodeLimitOrders = 10033,
    /// <summary>
    /// Volume of orders and positions reached the limit
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_LIMIT_VOLUME")] TradeRetcodeLimitVolume = 10034,
    /// <summary>
    /// Incorrect or prohibited order type
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_INVALID_ORDER")] TradeRetcodeInvalidOrder = 10035,
    /// <summary>
    /// Position already closed
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_POSITION_CLOSED")] TradeRetcodePositionClosed = 10036,
    /// <summary>
    /// Close volume exceeds position volume
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_INVALID_CLOSE_VOLUME")] TradeRetcodeInvalidCloseVolume = 10038,
    /// <summary>
    /// Close order already exists
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_CLOSE_ORDER_EXIST")] TradeRetcodeCloseOrderExist = 10039,
    /// <summary>
    /// Limit of open positions reached
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_LIMIT_POSITIONS")] TradeRetcodeLimitPositions = 10040,
    /// <summary>
    /// Pending order activation request rejected
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_REJECT_CANCEL")] TradeRetcodeRejectCancel = 10041,
    /// <summary>
    /// Only long positions allowed
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_LONG_ONLY")] TradeRetcodeLongOnly = 10042,
    /// <summary>
    /// Only short positions allowed
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_SHORT_ONLY")] TradeRetcodeShortOnly = 10043,
    /// <summary>
    /// Only position closing allowed
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_CLOSE_ONLY")] TradeRetcodeCloseOnly = 10044,
    /// <summary>
    /// Closing allowed only by FIFO rule
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_FIFO_CLOSE")] TradeRetcodeFifoClose = 10045,
    /// <summary>
    /// Opposite positions disabled
    /// </summary>
    [pbr::OriginalName("TRADE_RETCODE_HEDGE_PROHIBITED")] TradeRetcodeHedgeProhibited = 10046,
  }

  #endregion

  #region Messages
  public sealed partial class Error : pb::IMessage<Error>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Error> _parser = new pb::MessageParser<Error>(() => new Error());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Error> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mt5TermApi.MrpcMt5ErrorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Error() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Error(Error other) : this() {
      type_ = other.type_;
      errorCode_ = other.errorCode_;
      errorMessage_ = other.errorMessage_;
      mqlErrorCode_ = other.mqlErrorCode_;
      mqlErrorIntCode_ = other.mqlErrorIntCode_;
      mqlErrorDescription_ = other.mqlErrorDescription_;
      mqlErrorTradeCode_ = other.mqlErrorTradeCode_;
      mqlErrorTradeIntCode_ = other.mqlErrorTradeIntCode_;
      mqlErrorTradeDescription_ = other.mqlErrorTradeDescription_;
      stackTrace_ = other.stackTrace_;
      commandTypeName_ = other.commandTypeName_;
      commandId_ = other.commandId_;
      properties_ = other.properties_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Error Clone() {
      return new Error(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Mt5TermApi.ErrorType type_ = global::Mt5TermApi.ErrorType.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mt5TermApi.ErrorType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error_code" field.</summary>
    public const int ErrorCodeFieldNumber = 2;
    private string errorCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorCode {
      get { return errorCode_; }
      set {
        errorCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "error_message" field.</summary>
    public const int ErrorMessageFieldNumber = 3;
    private string errorMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorMessage {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mql_error_code" field.</summary>
    public const int MqlErrorCodeFieldNumber = 4;
    private global::Mt5TermApi.MqlErrorCode mqlErrorCode_ = global::Mt5TermApi.MqlErrorCode.ErrSuccess;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mt5TermApi.MqlErrorCode MqlErrorCode {
      get { return mqlErrorCode_; }
      set {
        mqlErrorCode_ = value;
      }
    }

    /// <summary>Field number for the "mql_error_int_code" field.</summary>
    public const int MqlErrorIntCodeFieldNumber = 5;
    private int mqlErrorIntCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MqlErrorIntCode {
      get { return mqlErrorIntCode_; }
      set {
        mqlErrorIntCode_ = value;
      }
    }

    /// <summary>Field number for the "mql_error_description" field.</summary>
    public const int MqlErrorDescriptionFieldNumber = 6;
    private string mqlErrorDescription_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MqlErrorDescription {
      get { return mqlErrorDescription_; }
      set {
        mqlErrorDescription_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mql_error_trade_code" field.</summary>
    public const int MqlErrorTradeCodeFieldNumber = 7;
    private global::Mt5TermApi.MqlErrorTradeCode mqlErrorTradeCode_ = global::Mt5TermApi.MqlErrorTradeCode.TradeRetcodeSuccess;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mt5TermApi.MqlErrorTradeCode MqlErrorTradeCode {
      get { return mqlErrorTradeCode_; }
      set {
        mqlErrorTradeCode_ = value;
      }
    }

    /// <summary>Field number for the "mql_error_trade_int_code" field.</summary>
    public const int MqlErrorTradeIntCodeFieldNumber = 8;
    private int mqlErrorTradeIntCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MqlErrorTradeIntCode {
      get { return mqlErrorTradeIntCode_; }
      set {
        mqlErrorTradeIntCode_ = value;
      }
    }

    /// <summary>Field number for the "mql_error_trade_description" field.</summary>
    public const int MqlErrorTradeDescriptionFieldNumber = 9;
    private string mqlErrorTradeDescription_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MqlErrorTradeDescription {
      get { return mqlErrorTradeDescription_; }
      set {
        mqlErrorTradeDescription_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "stack_trace" field.</summary>
    public const int StackTraceFieldNumber = 10;
    private string stackTrace_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StackTrace {
      get { return stackTrace_; }
      set {
        stackTrace_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "command_type_name" field.</summary>
    public const int CommandTypeNameFieldNumber = 11;
    private string commandTypeName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CommandTypeName {
      get { return commandTypeName_; }
      set {
        commandTypeName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "commandId" field.</summary>
    public const int CommandIdFieldNumber = 12;
    private long commandId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CommandId {
      get { return commandId_; }
      set {
        commandId_ = value;
      }
    }

    /// <summary>Field number for the "properties" field.</summary>
    public const int PropertiesFieldNumber = 13;
    private static readonly pb::FieldCodec<global::Mt5TermApi.ErrorProperty> _repeated_properties_codec
        = pb::FieldCodec.ForMessage(106, global::Mt5TermApi.ErrorProperty.Parser);
    private readonly pbc::RepeatedField<global::Mt5TermApi.ErrorProperty> properties_ = new pbc::RepeatedField<global::Mt5TermApi.ErrorProperty>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Mt5TermApi.ErrorProperty> Properties {
      get { return properties_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Error);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Error other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (ErrorCode != other.ErrorCode) return false;
      if (ErrorMessage != other.ErrorMessage) return false;
      if (MqlErrorCode != other.MqlErrorCode) return false;
      if (MqlErrorIntCode != other.MqlErrorIntCode) return false;
      if (MqlErrorDescription != other.MqlErrorDescription) return false;
      if (MqlErrorTradeCode != other.MqlErrorTradeCode) return false;
      if (MqlErrorTradeIntCode != other.MqlErrorTradeIntCode) return false;
      if (MqlErrorTradeDescription != other.MqlErrorTradeDescription) return false;
      if (StackTrace != other.StackTrace) return false;
      if (CommandTypeName != other.CommandTypeName) return false;
      if (CommandId != other.CommandId) return false;
      if(!properties_.Equals(other.properties_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Mt5TermApi.ErrorType.Undefined) hash ^= Type.GetHashCode();
      if (ErrorCode.Length != 0) hash ^= ErrorCode.GetHashCode();
      if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
      if (MqlErrorCode != global::Mt5TermApi.MqlErrorCode.ErrSuccess) hash ^= MqlErrorCode.GetHashCode();
      if (MqlErrorIntCode != 0) hash ^= MqlErrorIntCode.GetHashCode();
      if (MqlErrorDescription.Length != 0) hash ^= MqlErrorDescription.GetHashCode();
      if (MqlErrorTradeCode != global::Mt5TermApi.MqlErrorTradeCode.TradeRetcodeSuccess) hash ^= MqlErrorTradeCode.GetHashCode();
      if (MqlErrorTradeIntCode != 0) hash ^= MqlErrorTradeIntCode.GetHashCode();
      if (MqlErrorTradeDescription.Length != 0) hash ^= MqlErrorTradeDescription.GetHashCode();
      if (StackTrace.Length != 0) hash ^= StackTrace.GetHashCode();
      if (CommandTypeName.Length != 0) hash ^= CommandTypeName.GetHashCode();
      if (CommandId != 0L) hash ^= CommandId.GetHashCode();
      hash ^= properties_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Mt5TermApi.ErrorType.Undefined) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (ErrorCode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorCode);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ErrorMessage);
      }
      if (MqlErrorCode != global::Mt5TermApi.MqlErrorCode.ErrSuccess) {
        output.WriteRawTag(32);
        output.WriteEnum((int) MqlErrorCode);
      }
      if (MqlErrorIntCode != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(MqlErrorIntCode);
      }
      if (MqlErrorDescription.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(MqlErrorDescription);
      }
      if (MqlErrorTradeCode != global::Mt5TermApi.MqlErrorTradeCode.TradeRetcodeSuccess) {
        output.WriteRawTag(56);
        output.WriteEnum((int) MqlErrorTradeCode);
      }
      if (MqlErrorTradeIntCode != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(MqlErrorTradeIntCode);
      }
      if (MqlErrorTradeDescription.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(MqlErrorTradeDescription);
      }
      if (StackTrace.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(StackTrace);
      }
      if (CommandTypeName.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(CommandTypeName);
      }
      if (CommandId != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(CommandId);
      }
      properties_.WriteTo(output, _repeated_properties_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Mt5TermApi.ErrorType.Undefined) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (ErrorCode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorCode);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ErrorMessage);
      }
      if (MqlErrorCode != global::Mt5TermApi.MqlErrorCode.ErrSuccess) {
        output.WriteRawTag(32);
        output.WriteEnum((int) MqlErrorCode);
      }
      if (MqlErrorIntCode != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(MqlErrorIntCode);
      }
      if (MqlErrorDescription.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(MqlErrorDescription);
      }
      if (MqlErrorTradeCode != global::Mt5TermApi.MqlErrorTradeCode.TradeRetcodeSuccess) {
        output.WriteRawTag(56);
        output.WriteEnum((int) MqlErrorTradeCode);
      }
      if (MqlErrorTradeIntCode != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(MqlErrorTradeIntCode);
      }
      if (MqlErrorTradeDescription.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(MqlErrorTradeDescription);
      }
      if (StackTrace.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(StackTrace);
      }
      if (CommandTypeName.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(CommandTypeName);
      }
      if (CommandId != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(CommandId);
      }
      properties_.WriteTo(ref output, _repeated_properties_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Mt5TermApi.ErrorType.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (ErrorCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorCode);
      }
      if (ErrorMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      if (MqlErrorCode != global::Mt5TermApi.MqlErrorCode.ErrSuccess) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MqlErrorCode);
      }
      if (MqlErrorIntCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MqlErrorIntCode);
      }
      if (MqlErrorDescription.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MqlErrorDescription);
      }
      if (MqlErrorTradeCode != global::Mt5TermApi.MqlErrorTradeCode.TradeRetcodeSuccess) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MqlErrorTradeCode);
      }
      if (MqlErrorTradeIntCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MqlErrorTradeIntCode);
      }
      if (MqlErrorTradeDescription.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MqlErrorTradeDescription);
      }
      if (StackTrace.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StackTrace);
      }
      if (CommandTypeName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CommandTypeName);
      }
      if (CommandId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CommandId);
      }
      size += properties_.CalculateSize(_repeated_properties_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Error other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Mt5TermApi.ErrorType.Undefined) {
        Type = other.Type;
      }
      if (other.ErrorCode.Length != 0) {
        ErrorCode = other.ErrorCode;
      }
      if (other.ErrorMessage.Length != 0) {
        ErrorMessage = other.ErrorMessage;
      }
      if (other.MqlErrorCode != global::Mt5TermApi.MqlErrorCode.ErrSuccess) {
        MqlErrorCode = other.MqlErrorCode;
      }
      if (other.MqlErrorIntCode != 0) {
        MqlErrorIntCode = other.MqlErrorIntCode;
      }
      if (other.MqlErrorDescription.Length != 0) {
        MqlErrorDescription = other.MqlErrorDescription;
      }
      if (other.MqlErrorTradeCode != global::Mt5TermApi.MqlErrorTradeCode.TradeRetcodeSuccess) {
        MqlErrorTradeCode = other.MqlErrorTradeCode;
      }
      if (other.MqlErrorTradeIntCode != 0) {
        MqlErrorTradeIntCode = other.MqlErrorTradeIntCode;
      }
      if (other.MqlErrorTradeDescription.Length != 0) {
        MqlErrorTradeDescription = other.MqlErrorTradeDescription;
      }
      if (other.StackTrace.Length != 0) {
        StackTrace = other.StackTrace;
      }
      if (other.CommandTypeName.Length != 0) {
        CommandTypeName = other.CommandTypeName;
      }
      if (other.CommandId != 0L) {
        CommandId = other.CommandId;
      }
      properties_.Add(other.properties_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Mt5TermApi.ErrorType) input.ReadEnum();
            break;
          }
          case 18: {
            ErrorCode = input.ReadString();
            break;
          }
          case 26: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 32: {
            MqlErrorCode = (global::Mt5TermApi.MqlErrorCode) input.ReadEnum();
            break;
          }
          case 40: {
            MqlErrorIntCode = input.ReadInt32();
            break;
          }
          case 50: {
            MqlErrorDescription = input.ReadString();
            break;
          }
          case 56: {
            MqlErrorTradeCode = (global::Mt5TermApi.MqlErrorTradeCode) input.ReadEnum();
            break;
          }
          case 64: {
            MqlErrorTradeIntCode = input.ReadInt32();
            break;
          }
          case 74: {
            MqlErrorTradeDescription = input.ReadString();
            break;
          }
          case 82: {
            StackTrace = input.ReadString();
            break;
          }
          case 90: {
            CommandTypeName = input.ReadString();
            break;
          }
          case 96: {
            CommandId = input.ReadInt64();
            break;
          }
          case 106: {
            properties_.AddEntriesFrom(input, _repeated_properties_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Mt5TermApi.ErrorType) input.ReadEnum();
            break;
          }
          case 18: {
            ErrorCode = input.ReadString();
            break;
          }
          case 26: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 32: {
            MqlErrorCode = (global::Mt5TermApi.MqlErrorCode) input.ReadEnum();
            break;
          }
          case 40: {
            MqlErrorIntCode = input.ReadInt32();
            break;
          }
          case 50: {
            MqlErrorDescription = input.ReadString();
            break;
          }
          case 56: {
            MqlErrorTradeCode = (global::Mt5TermApi.MqlErrorTradeCode) input.ReadEnum();
            break;
          }
          case 64: {
            MqlErrorTradeIntCode = input.ReadInt32();
            break;
          }
          case 74: {
            MqlErrorTradeDescription = input.ReadString();
            break;
          }
          case 82: {
            StackTrace = input.ReadString();
            break;
          }
          case 90: {
            CommandTypeName = input.ReadString();
            break;
          }
          case 96: {
            CommandId = input.ReadInt64();
            break;
          }
          case 106: {
            properties_.AddEntriesFrom(ref input, _repeated_properties_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ErrorProperty : pb::IMessage<ErrorProperty>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ErrorProperty> _parser = new pb::MessageParser<ErrorProperty>(() => new ErrorProperty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ErrorProperty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mt5TermApi.MrpcMt5ErrorReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorProperty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorProperty(ErrorProperty other) : this() {
      errorArgKey_ = other.errorArgKey_;
      errorArgValue_ = other.errorArgValue_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorProperty Clone() {
      return new ErrorProperty(this);
    }

    /// <summary>Field number for the "error_arg_key" field.</summary>
    public const int ErrorArgKeyFieldNumber = 1;
    private string errorArgKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorArgKey {
      get { return errorArgKey_; }
      set {
        errorArgKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "error_arg_value" field.</summary>
    public const int ErrorArgValueFieldNumber = 2;
    private string errorArgValue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorArgValue {
      get { return errorArgValue_; }
      set {
        errorArgValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ErrorProperty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ErrorProperty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrorArgKey != other.ErrorArgKey) return false;
      if (ErrorArgValue != other.ErrorArgValue) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrorArgKey.Length != 0) hash ^= ErrorArgKey.GetHashCode();
      if (ErrorArgValue.Length != 0) hash ^= ErrorArgValue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrorArgKey.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ErrorArgKey);
      }
      if (ErrorArgValue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorArgValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrorArgKey.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ErrorArgKey);
      }
      if (ErrorArgValue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorArgValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ErrorArgKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorArgKey);
      }
      if (ErrorArgValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorArgValue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ErrorProperty other) {
      if (other == null) {
        return;
      }
      if (other.ErrorArgKey.Length != 0) {
        ErrorArgKey = other.ErrorArgKey;
      }
      if (other.ErrorArgValue.Length != 0) {
        ErrorArgValue = other.ErrorArgValue;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ErrorArgKey = input.ReadString();
            break;
          }
          case 18: {
            ErrorArgValue = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ErrorArgKey = input.ReadString();
            break;
          }
          case 18: {
            ErrorArgValue = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LogFileInfo : pb::IMessage<LogFileInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LogFileInfo> _parser = new pb::MessageParser<LogFileInfo>(() => new LogFileInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LogFileInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mt5TermApi.MrpcMt5ErrorReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogFileInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogFileInfo(LogFileInfo other) : this() {
      logType_ = other.logType_;
      fullPath_ = other.fullPath_;
      name_ = other.name_;
      content_ = other.content_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogFileInfo Clone() {
      return new LogFileInfo(this);
    }

    /// <summary>Field number for the "log_type" field.</summary>
    public const int LogTypeFieldNumber = 1;
    private global::Mt5TermApi.LogType logType_ = global::Mt5TermApi.LogType.Global;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mt5TermApi.LogType LogType {
      get { return logType_; }
      set {
        logType_ = value;
      }
    }

    /// <summary>Field number for the "full_path" field.</summary>
    public const int FullPathFieldNumber = 2;
    private string fullPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FullPath {
      get { return fullPath_; }
      set {
        fullPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 4;
    private string content_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LogFileInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LogFileInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LogType != other.LogType) return false;
      if (FullPath != other.FullPath) return false;
      if (Name != other.Name) return false;
      if (Content != other.Content) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LogType != global::Mt5TermApi.LogType.Global) hash ^= LogType.GetHashCode();
      if (FullPath.Length != 0) hash ^= FullPath.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LogType != global::Mt5TermApi.LogType.Global) {
        output.WriteRawTag(8);
        output.WriteEnum((int) LogType);
      }
      if (FullPath.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FullPath);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Content);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LogType != global::Mt5TermApi.LogType.Global) {
        output.WriteRawTag(8);
        output.WriteEnum((int) LogType);
      }
      if (FullPath.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FullPath);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Content);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LogType != global::Mt5TermApi.LogType.Global) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) LogType);
      }
      if (FullPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FullPath);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LogFileInfo other) {
      if (other == null) {
        return;
      }
      if (other.LogType != global::Mt5TermApi.LogType.Global) {
        LogType = other.LogType;
      }
      if (other.FullPath.Length != 0) {
        FullPath = other.FullPath;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LogType = (global::Mt5TermApi.LogType) input.ReadEnum();
            break;
          }
          case 18: {
            FullPath = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            Content = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LogType = (global::Mt5TermApi.LogType) input.ReadEnum();
            break;
          }
          case 18: {
            FullPath = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            Content = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
