// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mt5-term-api-demo-account.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace mt5_term_api {
  /// <summary>
  /// Demo account creation service.
  /// Automates the MT5 "Open an Account" wizard via Win32 GUI automation.
  /// Does NOT require 'id' header — auto-picks any available terminal.
  /// </summary>
  public static partial class DemoAccount
  {
    static readonly string __ServiceName = "mt5_term_api.DemoAccount";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoOpenAccountRequest> __Marshaller_mt5_term_api_GuiDemoOpenAccountRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoOpenAccountRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoOpenAccountReply> __Marshaller_mt5_term_api_GuiDemoOpenAccountReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoOpenAccountReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoInteractiveClientMessage> __Marshaller_mt5_term_api_GuiDemoInteractiveClientMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoInteractiveClientMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoInteractiveServerMessage> __Marshaller_mt5_term_api_GuiDemoInteractiveServerMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoInteractiveServerMessage.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.GuiDemoOpenAccountRequest, global::mt5_term_api.GuiDemoOpenAccountReply> __Method_OpenDemoAccount = new grpc::Method<global::mt5_term_api.GuiDemoOpenAccountRequest, global::mt5_term_api.GuiDemoOpenAccountReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "OpenDemoAccount",
        __Marshaller_mt5_term_api_GuiDemoOpenAccountRequest,
        __Marshaller_mt5_term_api_GuiDemoOpenAccountReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.GuiDemoInteractiveClientMessage, global::mt5_term_api.GuiDemoInteractiveServerMessage> __Method_DemoOpenAccountInteractive = new grpc::Method<global::mt5_term_api.GuiDemoInteractiveClientMessage, global::mt5_term_api.GuiDemoInteractiveServerMessage>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "DemoOpenAccountInteractive",
        __Marshaller_mt5_term_api_GuiDemoInteractiveClientMessage,
        __Marshaller_mt5_term_api_GuiDemoInteractiveServerMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::mt5_term_api.Mt5TermApiDemoAccountReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DemoAccount</summary>
    [grpc::BindServiceMethod(typeof(DemoAccount), "BindService")]
    public abstract partial class DemoAccountBase
    {
      /// <summary>
      /// Open a demo account. Full wizard flow: search → select → fill form → register.
      /// Returns login, password, and investor password for the new demo account.
      /// [DefaultValues]
      /// {
      ///   "company": "MetaQuotes Ltd.",
      ///   "firstName": "Test",
      ///   "lastName": "User",
      ///   "email": "test@test.com",
      ///   "phone": "+1234567890",
      ///   "timeoutSeconds": "60"
      /// }
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.GuiDemoOpenAccountReply> OpenDemoAccount(global::mt5_term_api.GuiDemoOpenAccountRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Interactive step-by-step demo account opening wizard.
      /// Bidirectional streaming session: search company -> select -> form schema -> submit -> 2FA (if any) -> completed.
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task DemoOpenAccountInteractive(grpc::IAsyncStreamReader<global::mt5_term_api.GuiDemoInteractiveClientMessage> requestStream, grpc::IServerStreamWriter<global::mt5_term_api.GuiDemoInteractiveServerMessage> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DemoAccount</summary>
    public partial class DemoAccountClient : grpc::ClientBase<DemoAccountClient>
    {
      /// <summary>Creates a new client for DemoAccount</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DemoAccountClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DemoAccount that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DemoAccountClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DemoAccountClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DemoAccountClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Open a demo account. Full wizard flow: search → select → fill form → register.
      /// Returns login, password, and investor password for the new demo account.
      /// [DefaultValues]
      /// {
      ///   "company": "MetaQuotes Ltd.",
      ///   "firstName": "Test",
      ///   "lastName": "User",
      ///   "email": "test@test.com",
      ///   "phone": "+1234567890",
      ///   "timeoutSeconds": "60"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiDemoOpenAccountReply OpenDemoAccount(global::mt5_term_api.GuiDemoOpenAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenDemoAccount(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Open a demo account. Full wizard flow: search → select → fill form → register.
      /// Returns login, password, and investor password for the new demo account.
      /// [DefaultValues]
      /// {
      ///   "company": "MetaQuotes Ltd.",
      ///   "firstName": "Test",
      ///   "lastName": "User",
      ///   "email": "test@test.com",
      ///   "phone": "+1234567890",
      ///   "timeoutSeconds": "60"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiDemoOpenAccountReply OpenDemoAccount(global::mt5_term_api.GuiDemoOpenAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_OpenDemoAccount, null, options, request);
      }
      /// <summary>
      /// Open a demo account. Full wizard flow: search → select → fill form → register.
      /// Returns login, password, and investor password for the new demo account.
      /// [DefaultValues]
      /// {
      ///   "company": "MetaQuotes Ltd.",
      ///   "firstName": "Test",
      ///   "lastName": "User",
      ///   "email": "test@test.com",
      ///   "phone": "+1234567890",
      ///   "timeoutSeconds": "60"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiDemoOpenAccountReply> OpenDemoAccountAsync(global::mt5_term_api.GuiDemoOpenAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenDemoAccountAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Open a demo account. Full wizard flow: search → select → fill form → register.
      /// Returns login, password, and investor password for the new demo account.
      /// [DefaultValues]
      /// {
      ///   "company": "MetaQuotes Ltd.",
      ///   "firstName": "Test",
      ///   "lastName": "User",
      ///   "email": "test@test.com",
      ///   "phone": "+1234567890",
      ///   "timeoutSeconds": "60"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiDemoOpenAccountReply> OpenDemoAccountAsync(global::mt5_term_api.GuiDemoOpenAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_OpenDemoAccount, null, options, request);
      }
      /// <summary>
      /// Interactive step-by-step demo account opening wizard.
      /// Bidirectional streaming session: search company -> select -> form schema -> submit -> 2FA (if any) -> completed.
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::mt5_term_api.GuiDemoInteractiveClientMessage, global::mt5_term_api.GuiDemoInteractiveServerMessage> DemoOpenAccountInteractive(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DemoOpenAccountInteractive(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Interactive step-by-step demo account opening wizard.
      /// Bidirectional streaming session: search company -> select -> form schema -> submit -> 2FA (if any) -> completed.
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::mt5_term_api.GuiDemoInteractiveClientMessage, global::mt5_term_api.GuiDemoInteractiveServerMessage> DemoOpenAccountInteractive(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_DemoOpenAccountInteractive, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override DemoAccountClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DemoAccountClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DemoAccountBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_OpenDemoAccount, serviceImpl.OpenDemoAccount)
          .AddMethod(__Method_DemoOpenAccountInteractive, serviceImpl.DemoOpenAccountInteractive).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DemoAccountBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_OpenDemoAccount, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.GuiDemoOpenAccountRequest, global::mt5_term_api.GuiDemoOpenAccountReply>(serviceImpl.OpenDemoAccount));
      serviceBinder.AddMethod(__Method_DemoOpenAccountInteractive, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::mt5_term_api.GuiDemoInteractiveClientMessage, global::mt5_term_api.GuiDemoInteractiveServerMessage>(serviceImpl.DemoOpenAccountInteractive));
    }

  }
}
#endregion
