// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mt5-term-api-gui.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace mt5_term_api {
  public static partial class Gui
  {
    static readonly string __ServiceName = "mt5_term_api.Gui";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiLoginRequest> __Marshaller_mt5_term_api_GuiLoginRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiLoginRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiLoginReply> __Marshaller_mt5_term_api_GuiLoginReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiLoginReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiBrokerSearchRequest> __Marshaller_mt5_term_api_GuiBrokerSearchRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiBrokerSearchRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiBrokerSearchReply> __Marshaller_mt5_term_api_GuiBrokerSearchReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiBrokerSearchReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiLoginExRequest> __Marshaller_mt5_term_api_GuiLoginExRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiLoginExRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiLoginExReply> __Marshaller_mt5_term_api_GuiLoginExReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiLoginExReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiCloseDialogsRequest> __Marshaller_mt5_term_api_GuiCloseDialogsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiCloseDialogsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiCloseDialogsReply> __Marshaller_mt5_term_api_GuiCloseDialogsReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiCloseDialogsReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoFindCompaniesRequest> __Marshaller_mt5_term_api_GuiDemoFindCompaniesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoFindCompaniesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoFindCompaniesReply> __Marshaller_mt5_term_api_GuiDemoFindCompaniesReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoFindCompaniesReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoServersAndTypesRequest> __Marshaller_mt5_term_api_GuiDemoServersAndTypesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoServersAndTypesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoServersAndTypesReply> __Marshaller_mt5_term_api_GuiDemoServersAndTypesReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoServersAndTypesReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoOpenAccountRequest> __Marshaller_mt5_term_api_GuiDemoOpenAccountRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoOpenAccountRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoOpenAccountReply> __Marshaller_mt5_term_api_GuiDemoOpenAccountReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoOpenAccountReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoEnumControlsRequest> __Marshaller_mt5_term_api_GuiDemoEnumControlsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoEnumControlsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoEnumControlsReply> __Marshaller_mt5_term_api_GuiDemoEnumControlsReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoEnumControlsReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoProgressEvent> __Marshaller_mt5_term_api_GuiDemoProgressEvent = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoProgressEvent.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoInteractiveClientMessage> __Marshaller_mt5_term_api_GuiDemoInteractiveClientMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoInteractiveClientMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GuiDemoInteractiveServerMessage> __Marshaller_mt5_term_api_GuiDemoInteractiveServerMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GuiDemoInteractiveServerMessage.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.GuiLoginRequest, global::mt5_term_api.GuiLoginReply> __Method_Login = new grpc::Method<global::mt5_term_api.GuiLoginRequest, global::mt5_term_api.GuiLoginReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Login",
        __Marshaller_mt5_term_api_GuiLoginRequest,
        __Marshaller_mt5_term_api_GuiLoginReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.GuiBrokerSearchRequest, global::mt5_term_api.GuiBrokerSearchReply> __Method_BrokerSearch = new grpc::Method<global::mt5_term_api.GuiBrokerSearchRequest, global::mt5_term_api.GuiBrokerSearchReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BrokerSearch",
        __Marshaller_mt5_term_api_GuiBrokerSearchRequest,
        __Marshaller_mt5_term_api_GuiBrokerSearchReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.GuiLoginExRequest, global::mt5_term_api.GuiLoginExReply> __Method_LoginEx = new grpc::Method<global::mt5_term_api.GuiLoginExRequest, global::mt5_term_api.GuiLoginExReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "LoginEx",
        __Marshaller_mt5_term_api_GuiLoginExRequest,
        __Marshaller_mt5_term_api_GuiLoginExReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.GuiCloseDialogsRequest, global::mt5_term_api.GuiCloseDialogsReply> __Method_CloseDialogs = new grpc::Method<global::mt5_term_api.GuiCloseDialogsRequest, global::mt5_term_api.GuiCloseDialogsReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CloseDialogs",
        __Marshaller_mt5_term_api_GuiCloseDialogsRequest,
        __Marshaller_mt5_term_api_GuiCloseDialogsReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.GuiDemoFindCompaniesRequest, global::mt5_term_api.GuiDemoFindCompaniesReply> __Method_DemoFindCompanies = new grpc::Method<global::mt5_term_api.GuiDemoFindCompaniesRequest, global::mt5_term_api.GuiDemoFindCompaniesReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DemoFindCompanies",
        __Marshaller_mt5_term_api_GuiDemoFindCompaniesRequest,
        __Marshaller_mt5_term_api_GuiDemoFindCompaniesReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.GuiDemoServersAndTypesRequest, global::mt5_term_api.GuiDemoServersAndTypesReply> __Method_DemoServersAndTypes = new grpc::Method<global::mt5_term_api.GuiDemoServersAndTypesRequest, global::mt5_term_api.GuiDemoServersAndTypesReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DemoServersAndTypes",
        __Marshaller_mt5_term_api_GuiDemoServersAndTypesRequest,
        __Marshaller_mt5_term_api_GuiDemoServersAndTypesReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.GuiDemoOpenAccountRequest, global::mt5_term_api.GuiDemoOpenAccountReply> __Method_DemoOpenAccount = new grpc::Method<global::mt5_term_api.GuiDemoOpenAccountRequest, global::mt5_term_api.GuiDemoOpenAccountReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DemoOpenAccount",
        __Marshaller_mt5_term_api_GuiDemoOpenAccountRequest,
        __Marshaller_mt5_term_api_GuiDemoOpenAccountReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.GuiDemoEnumControlsRequest, global::mt5_term_api.GuiDemoEnumControlsReply> __Method_DemoEnumControls = new grpc::Method<global::mt5_term_api.GuiDemoEnumControlsRequest, global::mt5_term_api.GuiDemoEnumControlsReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DemoEnumControls",
        __Marshaller_mt5_term_api_GuiDemoEnumControlsRequest,
        __Marshaller_mt5_term_api_GuiDemoEnumControlsReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.GuiDemoOpenAccountRequest, global::mt5_term_api.GuiDemoProgressEvent> __Method_DemoOpenAccountWithProgress = new grpc::Method<global::mt5_term_api.GuiDemoOpenAccountRequest, global::mt5_term_api.GuiDemoProgressEvent>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "DemoOpenAccountWithProgress",
        __Marshaller_mt5_term_api_GuiDemoOpenAccountRequest,
        __Marshaller_mt5_term_api_GuiDemoProgressEvent);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.GuiDemoInteractiveClientMessage, global::mt5_term_api.GuiDemoInteractiveServerMessage> __Method_DemoOpenAccountInteractive = new grpc::Method<global::mt5_term_api.GuiDemoInteractiveClientMessage, global::mt5_term_api.GuiDemoInteractiveServerMessage>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "DemoOpenAccountInteractive",
        __Marshaller_mt5_term_api_GuiDemoInteractiveClientMessage,
        __Marshaller_mt5_term_api_GuiDemoInteractiveServerMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::mt5_term_api.Mt5TermApiGuiReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Gui</summary>
    [grpc::BindServiceMethod(typeof(Gui), "BindService")]
    public abstract partial class GuiBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.GuiLoginReply> Login(global::mt5_term_api.GuiLoginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.GuiBrokerSearchReply> BrokerSearch(global::mt5_term_api.GuiBrokerSearchRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.GuiLoginExReply> LoginEx(global::mt5_term_api.GuiLoginExRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.GuiCloseDialogsReply> CloseDialogs(global::mt5_term_api.GuiCloseDialogsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.GuiDemoFindCompaniesReply> DemoFindCompanies(global::mt5_term_api.GuiDemoFindCompaniesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.GuiDemoServersAndTypesReply> DemoServersAndTypes(global::mt5_term_api.GuiDemoServersAndTypesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.GuiDemoOpenAccountReply> DemoOpenAccount(global::mt5_term_api.GuiDemoOpenAccountRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.GuiDemoEnumControlsReply> DemoEnumControls(global::mt5_term_api.GuiDemoEnumControlsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task DemoOpenAccountWithProgress(global::mt5_term_api.GuiDemoOpenAccountRequest request, grpc::IServerStreamWriter<global::mt5_term_api.GuiDemoProgressEvent> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task DemoOpenAccountInteractive(grpc::IAsyncStreamReader<global::mt5_term_api.GuiDemoInteractiveClientMessage> requestStream, grpc::IServerStreamWriter<global::mt5_term_api.GuiDemoInteractiveServerMessage> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Gui</summary>
    public partial class GuiClient : grpc::ClientBase<GuiClient>
    {
      /// <summary>Creates a new client for Gui</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public GuiClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Gui that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public GuiClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected GuiClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected GuiClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiLoginReply Login(global::mt5_term_api.GuiLoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiLoginReply Login(global::mt5_term_api.GuiLoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Login, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiLoginReply> LoginAsync(global::mt5_term_api.GuiLoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiLoginReply> LoginAsync(global::mt5_term_api.GuiLoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Login, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiBrokerSearchReply BrokerSearch(global::mt5_term_api.GuiBrokerSearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BrokerSearch(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiBrokerSearchReply BrokerSearch(global::mt5_term_api.GuiBrokerSearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BrokerSearch, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiBrokerSearchReply> BrokerSearchAsync(global::mt5_term_api.GuiBrokerSearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BrokerSearchAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiBrokerSearchReply> BrokerSearchAsync(global::mt5_term_api.GuiBrokerSearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BrokerSearch, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiLoginExReply LoginEx(global::mt5_term_api.GuiLoginExRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginEx(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiLoginExReply LoginEx(global::mt5_term_api.GuiLoginExRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_LoginEx, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiLoginExReply> LoginExAsync(global::mt5_term_api.GuiLoginExRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginExAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiLoginExReply> LoginExAsync(global::mt5_term_api.GuiLoginExRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_LoginEx, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiCloseDialogsReply CloseDialogs(global::mt5_term_api.GuiCloseDialogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CloseDialogs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiCloseDialogsReply CloseDialogs(global::mt5_term_api.GuiCloseDialogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CloseDialogs, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiCloseDialogsReply> CloseDialogsAsync(global::mt5_term_api.GuiCloseDialogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CloseDialogsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiCloseDialogsReply> CloseDialogsAsync(global::mt5_term_api.GuiCloseDialogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CloseDialogs, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiDemoFindCompaniesReply DemoFindCompanies(global::mt5_term_api.GuiDemoFindCompaniesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DemoFindCompanies(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiDemoFindCompaniesReply DemoFindCompanies(global::mt5_term_api.GuiDemoFindCompaniesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DemoFindCompanies, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiDemoFindCompaniesReply> DemoFindCompaniesAsync(global::mt5_term_api.GuiDemoFindCompaniesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DemoFindCompaniesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiDemoFindCompaniesReply> DemoFindCompaniesAsync(global::mt5_term_api.GuiDemoFindCompaniesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DemoFindCompanies, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiDemoServersAndTypesReply DemoServersAndTypes(global::mt5_term_api.GuiDemoServersAndTypesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DemoServersAndTypes(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiDemoServersAndTypesReply DemoServersAndTypes(global::mt5_term_api.GuiDemoServersAndTypesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DemoServersAndTypes, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiDemoServersAndTypesReply> DemoServersAndTypesAsync(global::mt5_term_api.GuiDemoServersAndTypesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DemoServersAndTypesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiDemoServersAndTypesReply> DemoServersAndTypesAsync(global::mt5_term_api.GuiDemoServersAndTypesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DemoServersAndTypes, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiDemoOpenAccountReply DemoOpenAccount(global::mt5_term_api.GuiDemoOpenAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DemoOpenAccount(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiDemoOpenAccountReply DemoOpenAccount(global::mt5_term_api.GuiDemoOpenAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DemoOpenAccount, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiDemoOpenAccountReply> DemoOpenAccountAsync(global::mt5_term_api.GuiDemoOpenAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DemoOpenAccountAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiDemoOpenAccountReply> DemoOpenAccountAsync(global::mt5_term_api.GuiDemoOpenAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DemoOpenAccount, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiDemoEnumControlsReply DemoEnumControls(global::mt5_term_api.GuiDemoEnumControlsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DemoEnumControls(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GuiDemoEnumControlsReply DemoEnumControls(global::mt5_term_api.GuiDemoEnumControlsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DemoEnumControls, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiDemoEnumControlsReply> DemoEnumControlsAsync(global::mt5_term_api.GuiDemoEnumControlsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DemoEnumControlsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GuiDemoEnumControlsReply> DemoEnumControlsAsync(global::mt5_term_api.GuiDemoEnumControlsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DemoEnumControls, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::mt5_term_api.GuiDemoProgressEvent> DemoOpenAccountWithProgress(global::mt5_term_api.GuiDemoOpenAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DemoOpenAccountWithProgress(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::mt5_term_api.GuiDemoProgressEvent> DemoOpenAccountWithProgress(global::mt5_term_api.GuiDemoOpenAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_DemoOpenAccountWithProgress, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::mt5_term_api.GuiDemoInteractiveClientMessage, global::mt5_term_api.GuiDemoInteractiveServerMessage> DemoOpenAccountInteractive(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DemoOpenAccountInteractive(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::mt5_term_api.GuiDemoInteractiveClientMessage, global::mt5_term_api.GuiDemoInteractiveServerMessage> DemoOpenAccountInteractive(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_DemoOpenAccountInteractive, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override GuiClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GuiClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(GuiBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Login, serviceImpl.Login)
          .AddMethod(__Method_BrokerSearch, serviceImpl.BrokerSearch)
          .AddMethod(__Method_LoginEx, serviceImpl.LoginEx)
          .AddMethod(__Method_CloseDialogs, serviceImpl.CloseDialogs)
          .AddMethod(__Method_DemoFindCompanies, serviceImpl.DemoFindCompanies)
          .AddMethod(__Method_DemoServersAndTypes, serviceImpl.DemoServersAndTypes)
          .AddMethod(__Method_DemoOpenAccount, serviceImpl.DemoOpenAccount)
          .AddMethod(__Method_DemoEnumControls, serviceImpl.DemoEnumControls)
          .AddMethod(__Method_DemoOpenAccountWithProgress, serviceImpl.DemoOpenAccountWithProgress)
          .AddMethod(__Method_DemoOpenAccountInteractive, serviceImpl.DemoOpenAccountInteractive).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GuiBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Login, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.GuiLoginRequest, global::mt5_term_api.GuiLoginReply>(serviceImpl.Login));
      serviceBinder.AddMethod(__Method_BrokerSearch, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.GuiBrokerSearchRequest, global::mt5_term_api.GuiBrokerSearchReply>(serviceImpl.BrokerSearch));
      serviceBinder.AddMethod(__Method_LoginEx, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.GuiLoginExRequest, global::mt5_term_api.GuiLoginExReply>(serviceImpl.LoginEx));
      serviceBinder.AddMethod(__Method_CloseDialogs, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.GuiCloseDialogsRequest, global::mt5_term_api.GuiCloseDialogsReply>(serviceImpl.CloseDialogs));
      serviceBinder.AddMethod(__Method_DemoFindCompanies, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.GuiDemoFindCompaniesRequest, global::mt5_term_api.GuiDemoFindCompaniesReply>(serviceImpl.DemoFindCompanies));
      serviceBinder.AddMethod(__Method_DemoServersAndTypes, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.GuiDemoServersAndTypesRequest, global::mt5_term_api.GuiDemoServersAndTypesReply>(serviceImpl.DemoServersAndTypes));
      serviceBinder.AddMethod(__Method_DemoOpenAccount, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.GuiDemoOpenAccountRequest, global::mt5_term_api.GuiDemoOpenAccountReply>(serviceImpl.DemoOpenAccount));
      serviceBinder.AddMethod(__Method_DemoEnumControls, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.GuiDemoEnumControlsRequest, global::mt5_term_api.GuiDemoEnumControlsReply>(serviceImpl.DemoEnumControls));
      serviceBinder.AddMethod(__Method_DemoOpenAccountWithProgress, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::mt5_term_api.GuiDemoOpenAccountRequest, global::mt5_term_api.GuiDemoProgressEvent>(serviceImpl.DemoOpenAccountWithProgress));
      serviceBinder.AddMethod(__Method_DemoOpenAccountInteractive, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::mt5_term_api.GuiDemoInteractiveClientMessage, global::mt5_term_api.GuiDemoInteractiveServerMessage>(serviceImpl.DemoOpenAccountInteractive));
    }

  }
}
#endregion
