// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mt5-term-api-trade-stats.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace mt5_term_api {
  public static partial class TradeStats
  {
    static readonly string __ServiceName = "mt5_term_api.TradeStats";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.TradeStatsRequest> __Marshaller_mt5_term_api_TradeStatsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.TradeStatsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.TradeStatsReply> __Marshaller_mt5_term_api_TradeStatsReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.TradeStatsReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.TradeStatsEquityHistoryRequest> __Marshaller_mt5_term_api_TradeStatsEquityHistoryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.TradeStatsEquityHistoryRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.TradeStatsEquityHistoryReply> __Marshaller_mt5_term_api_TradeStatsEquityHistoryReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.TradeStatsEquityHistoryReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.EquityHistoryRequest> __Marshaller_mt5_term_api_EquityHistoryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.EquityHistoryRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.EquityHistoryReply> __Marshaller_mt5_term_api_EquityHistoryReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.EquityHistoryReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.TradeUnrealizedPLRequest> __Marshaller_mt5_term_api_TradeUnrealizedPLRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.TradeUnrealizedPLRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.TradeUnrealizedPLReply> __Marshaller_mt5_term_api_TradeUnrealizedPLReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.TradeUnrealizedPLReply.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.TradeStatsRequest, global::mt5_term_api.TradeStatsReply> __Method_TradeStats = new grpc::Method<global::mt5_term_api.TradeStatsRequest, global::mt5_term_api.TradeStatsReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TradeStats",
        __Marshaller_mt5_term_api_TradeStatsRequest,
        __Marshaller_mt5_term_api_TradeStatsReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.TradeStatsEquityHistoryRequest, global::mt5_term_api.TradeStatsEquityHistoryReply> __Method_TradeStatsEquityHistory = new grpc::Method<global::mt5_term_api.TradeStatsEquityHistoryRequest, global::mt5_term_api.TradeStatsEquityHistoryReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TradeStatsEquityHistory",
        __Marshaller_mt5_term_api_TradeStatsEquityHistoryRequest,
        __Marshaller_mt5_term_api_TradeStatsEquityHistoryReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.EquityHistoryRequest, global::mt5_term_api.EquityHistoryReply> __Method_EquityHistory = new grpc::Method<global::mt5_term_api.EquityHistoryRequest, global::mt5_term_api.EquityHistoryReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "EquityHistory",
        __Marshaller_mt5_term_api_EquityHistoryRequest,
        __Marshaller_mt5_term_api_EquityHistoryReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.TradeUnrealizedPLRequest, global::mt5_term_api.TradeUnrealizedPLReply> __Method_TradeUnrealizedPL = new grpc::Method<global::mt5_term_api.TradeUnrealizedPLRequest, global::mt5_term_api.TradeUnrealizedPLReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TradeUnrealizedPL",
        __Marshaller_mt5_term_api_TradeUnrealizedPLRequest,
        __Marshaller_mt5_term_api_TradeUnrealizedPLReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::mt5_term_api.Mt5TermApiTradeStatsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TradeStats</summary>
    [grpc::BindServiceMethod(typeof(TradeStats), "BindService")]
    public abstract partial class TradeStatsBase
    {
      /// <summary>
      /// Trading statistics calculated from order history and open orders
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00"
      /// }
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.TradeStatsReply> TradeStats(global::mt5_term_api.TradeStatsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Trading statistics with equity history chart points
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00",
      ///   "excludeSameBars": true
      /// }
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.TradeStatsEquityHistoryReply> TradeStatsEquityHistory(global::mt5_term_api.TradeStatsEquityHistoryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Equity history curve points with drawdown calculation
      /// [DefaultValues]
      /// {
      ///   "from": "2024-10-01T00:00:00",
      ///   "excludeSameBars": true
      /// }
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.EquityHistoryReply> EquityHistory(global::mt5_term_api.EquityHistoryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Maximum and minimum unrealized profit/loss per trade
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00"
      /// }
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.TradeUnrealizedPLReply> TradeUnrealizedPL(global::mt5_term_api.TradeUnrealizedPLRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TradeStats</summary>
    public partial class TradeStatsClient : grpc::ClientBase<TradeStatsClient>
    {
      /// <summary>Creates a new client for TradeStats</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TradeStatsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TradeStats that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TradeStatsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TradeStatsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TradeStatsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Trading statistics calculated from order history and open orders
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.TradeStatsReply TradeStats(global::mt5_term_api.TradeStatsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TradeStats(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Trading statistics calculated from order history and open orders
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.TradeStatsReply TradeStats(global::mt5_term_api.TradeStatsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TradeStats, null, options, request);
      }
      /// <summary>
      /// Trading statistics calculated from order history and open orders
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.TradeStatsReply> TradeStatsAsync(global::mt5_term_api.TradeStatsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TradeStatsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Trading statistics calculated from order history and open orders
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.TradeStatsReply> TradeStatsAsync(global::mt5_term_api.TradeStatsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TradeStats, null, options, request);
      }
      /// <summary>
      /// Trading statistics with equity history chart points
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00",
      ///   "excludeSameBars": true
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.TradeStatsEquityHistoryReply TradeStatsEquityHistory(global::mt5_term_api.TradeStatsEquityHistoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TradeStatsEquityHistory(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Trading statistics with equity history chart points
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00",
      ///   "excludeSameBars": true
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.TradeStatsEquityHistoryReply TradeStatsEquityHistory(global::mt5_term_api.TradeStatsEquityHistoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TradeStatsEquityHistory, null, options, request);
      }
      /// <summary>
      /// Trading statistics with equity history chart points
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00",
      ///   "excludeSameBars": true
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.TradeStatsEquityHistoryReply> TradeStatsEquityHistoryAsync(global::mt5_term_api.TradeStatsEquityHistoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TradeStatsEquityHistoryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Trading statistics with equity history chart points
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00",
      ///   "excludeSameBars": true
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.TradeStatsEquityHistoryReply> TradeStatsEquityHistoryAsync(global::mt5_term_api.TradeStatsEquityHistoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TradeStatsEquityHistory, null, options, request);
      }
      /// <summary>
      /// Equity history curve points with drawdown calculation
      /// [DefaultValues]
      /// {
      ///   "from": "2024-10-01T00:00:00",
      ///   "excludeSameBars": true
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.EquityHistoryReply EquityHistory(global::mt5_term_api.EquityHistoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EquityHistory(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Equity history curve points with drawdown calculation
      /// [DefaultValues]
      /// {
      ///   "from": "2024-10-01T00:00:00",
      ///   "excludeSameBars": true
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.EquityHistoryReply EquityHistory(global::mt5_term_api.EquityHistoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_EquityHistory, null, options, request);
      }
      /// <summary>
      /// Equity history curve points with drawdown calculation
      /// [DefaultValues]
      /// {
      ///   "from": "2024-10-01T00:00:00",
      ///   "excludeSameBars": true
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.EquityHistoryReply> EquityHistoryAsync(global::mt5_term_api.EquityHistoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EquityHistoryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Equity history curve points with drawdown calculation
      /// [DefaultValues]
      /// {
      ///   "from": "2024-10-01T00:00:00",
      ///   "excludeSameBars": true
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.EquityHistoryReply> EquityHistoryAsync(global::mt5_term_api.EquityHistoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_EquityHistory, null, options, request);
      }
      /// <summary>
      /// Maximum and minimum unrealized profit/loss per trade
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.TradeUnrealizedPLReply TradeUnrealizedPL(global::mt5_term_api.TradeUnrealizedPLRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TradeUnrealizedPL(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Maximum and minimum unrealized profit/loss per trade
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.TradeUnrealizedPLReply TradeUnrealizedPL(global::mt5_term_api.TradeUnrealizedPLRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TradeUnrealizedPL, null, options, request);
      }
      /// <summary>
      /// Maximum and minimum unrealized profit/loss per trade
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.TradeUnrealizedPLReply> TradeUnrealizedPLAsync(global::mt5_term_api.TradeUnrealizedPLRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TradeUnrealizedPLAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Maximum and minimum unrealized profit/loss per trade
      /// [DefaultValues]
      /// {
      ///   "from": "2024-01-01T00:00:00"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.TradeUnrealizedPLReply> TradeUnrealizedPLAsync(global::mt5_term_api.TradeUnrealizedPLRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TradeUnrealizedPL, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override TradeStatsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TradeStatsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(TradeStatsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_TradeStats, serviceImpl.TradeStats)
          .AddMethod(__Method_TradeStatsEquityHistory, serviceImpl.TradeStatsEquityHistory)
          .AddMethod(__Method_EquityHistory, serviceImpl.EquityHistory)
          .AddMethod(__Method_TradeUnrealizedPL, serviceImpl.TradeUnrealizedPL).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TradeStatsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_TradeStats, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.TradeStatsRequest, global::mt5_term_api.TradeStatsReply>(serviceImpl.TradeStats));
      serviceBinder.AddMethod(__Method_TradeStatsEquityHistory, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.TradeStatsEquityHistoryRequest, global::mt5_term_api.TradeStatsEquityHistoryReply>(serviceImpl.TradeStatsEquityHistory));
      serviceBinder.AddMethod(__Method_EquityHistory, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.EquityHistoryRequest, global::mt5_term_api.EquityHistoryReply>(serviceImpl.EquityHistory));
      serviceBinder.AddMethod(__Method_TradeUnrealizedPL, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.TradeUnrealizedPLRequest, global::mt5_term_api.TradeUnrealizedPLReply>(serviceImpl.TradeUnrealizedPL));
    }

  }
}
#endregion
