// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mt5-term-api-charts.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace mt5_term_api {
  public static partial class Charts
  {
    static readonly string __ServiceName = "mt5_term_api.Charts";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.OpenTerminalChartWithEaRequest> __Marshaller_mt5_term_api_OpenTerminalChartWithEaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.OpenTerminalChartWithEaRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.OpenTerminalChartWithEaReply> __Marshaller_mt5_term_api_OpenTerminalChartWithEaReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.OpenTerminalChartWithEaReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GetEaParamsRequest> __Marshaller_mt5_term_api_GetEaParamsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GetEaParamsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt5_term_api.GetEaParamsReply> __Marshaller_mt5_term_api_GetEaParamsReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt5_term_api.GetEaParamsReply.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.OpenTerminalChartWithEaRequest, global::mt5_term_api.OpenTerminalChartWithEaReply> __Method_OpenTerminalChartWithEa = new grpc::Method<global::mt5_term_api.OpenTerminalChartWithEaRequest, global::mt5_term_api.OpenTerminalChartWithEaReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "OpenTerminalChartWithEa",
        __Marshaller_mt5_term_api_OpenTerminalChartWithEaRequest,
        __Marshaller_mt5_term_api_OpenTerminalChartWithEaReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt5_term_api.GetEaParamsRequest, global::mt5_term_api.GetEaParamsReply> __Method_GetEaParams = new grpc::Method<global::mt5_term_api.GetEaParamsRequest, global::mt5_term_api.GetEaParamsReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetEaParams",
        __Marshaller_mt5_term_api_GetEaParamsRequest,
        __Marshaller_mt5_term_api_GetEaParamsReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::mt5_term_api.Mt5TermApiChartsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Charts</summary>
    [grpc::BindServiceMethod(typeof(Charts), "BindService")]
    public abstract partial class ChartsBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.OpenTerminalChartWithEaReply> OpenTerminalChartWithEa(global::mt5_term_api.OpenTerminalChartWithEaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt5_term_api.GetEaParamsReply> GetEaParams(global::mt5_term_api.GetEaParamsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Charts</summary>
    public partial class ChartsClient : grpc::ClientBase<ChartsClient>
    {
      /// <summary>Creates a new client for Charts</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ChartsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Charts that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ChartsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ChartsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ChartsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.OpenTerminalChartWithEaReply OpenTerminalChartWithEa(global::mt5_term_api.OpenTerminalChartWithEaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenTerminalChartWithEa(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.OpenTerminalChartWithEaReply OpenTerminalChartWithEa(global::mt5_term_api.OpenTerminalChartWithEaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_OpenTerminalChartWithEa, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.OpenTerminalChartWithEaReply> OpenTerminalChartWithEaAsync(global::mt5_term_api.OpenTerminalChartWithEaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenTerminalChartWithEaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.OpenTerminalChartWithEaReply> OpenTerminalChartWithEaAsync(global::mt5_term_api.OpenTerminalChartWithEaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_OpenTerminalChartWithEa, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GetEaParamsReply GetEaParams(global::mt5_term_api.GetEaParamsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetEaParams(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt5_term_api.GetEaParamsReply GetEaParams(global::mt5_term_api.GetEaParamsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetEaParams, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GetEaParamsReply> GetEaParamsAsync(global::mt5_term_api.GetEaParamsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetEaParamsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt5_term_api.GetEaParamsReply> GetEaParamsAsync(global::mt5_term_api.GetEaParamsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetEaParams, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ChartsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ChartsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ChartsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_OpenTerminalChartWithEa, serviceImpl.OpenTerminalChartWithEa)
          .AddMethod(__Method_GetEaParams, serviceImpl.GetEaParams).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ChartsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_OpenTerminalChartWithEa, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.OpenTerminalChartWithEaRequest, global::mt5_term_api.OpenTerminalChartWithEaReply>(serviceImpl.OpenTerminalChartWithEa));
      serviceBinder.AddMethod(__Method_GetEaParams, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt5_term_api.GetEaParamsRequest, global::mt5_term_api.GetEaParamsReply>(serviceImpl.GetEaParams));
    }

  }
}
#endregion
