// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mt5-term-api-admin.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace mrpc_admin {

  /// <summary>Holder for reflection information generated from mt5-term-api-admin.proto</summary>
  public static partial class Mt5TermApiAdminReflection {

    #region Descriptor
    /// <summary>File descriptor for mt5-term-api-admin.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Mt5TermApiAdminReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhtdDUtdGVybS1hcGktYWRtaW4ucHJvdG8SCm1ycGNfYWRtaW4aHGdvb2ds",
            "ZS9hcGkvYW5ub3RhdGlvbnMucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1l",
            "c3RhbXAucHJvdG8idwoLVXNhZ2VTYW1wbGUSKAoEdGltZRgBIAEoCzIaLmdv",
            "b2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASEwoLY3B1X3BlcmNlbnQYAiABKAES",
            "EwoLcmFtX3VzZWRfbWIYAyABKAQSFAoMcmFtX3RvdGFsX21iGAQgASgEIosB",
            "ChBTeXN0ZW1Vc2FnZVJlcGx5EhMKC2NwdV9wZXJjZW50GAEgASgBEhMKC3Jh",
            "bV91c2VkX21iGAIgASgEEhQKDHJhbV90b3RhbF9tYhgDIAEoBBIoCgdoaXN0",
            "b3J5GAQgAygLMhcubXJwY19hZG1pbi5Vc2FnZVNhbXBsZRINCgVlcnJvchgF",
            "IAEoCSIrChZBY3RpdmVUZXJtaW5hbHNSZXF1ZXN0EhEKCWFkbWluX2tleRgB",
            "IAEoCSK+AQoMVGVybWluYWxJbmZvEgoKAmlkGAEgASgJEhMKC3VzZXJfbnVt",
            "YmVyGAIgASgNEhQKDHdpbmRvd3NfdXNlchgDIAEoCRIPCgdhY2NvdW50GAQg",
            "ASgEEg4KBnNlcnZlchgFIAEoCRIMCgRwb3J0GAYgASgNEi4KCmNyZWF0ZWRf",
            "YXQYByABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhgKEHdpbmRv",
            "d3NfcGFzc3dvcmQYCCABKAki7QEKFEFjdGl2ZVRlcm1pbmFsc1JlcGx5EgsK",
            "A3BvZBgBIAEoCRIMCgRub2RlGAIgASgJEg4KBnBvZF9pcBgDIAEoCRIrCgl0",
            "ZXJtaW5hbHMYBCADKAsyGC5tcnBjX2FkbWluLlRlcm1pbmFsSW5mbxINCgVl",
            "cnJvchgFIAEoCRITCgtjcHVfcGVyY2VudBgGIAEoARITCgtyYW1fdXNlZF9t",
            "YhgHIAEoBBIUCgxyYW1fdG90YWxfbWIYCCABKAQSLgoNdXNhZ2VfaGlzdG9y",
            "eRgJIAMoCzIXLm1ycGNfYWRtaW4uVXNhZ2VTYW1wbGUiiQIKDFBvZFRlcm1p",
            "bmFscxILCgNwb2QYASABKAkSDAoEbm9kZRgCIAEoCRIOCgZwb2RfaXAYAyAB",
            "KAkSEQoJbm92bmNfdXJsGAQgASgJEisKCXRlcm1pbmFscxgFIAMoCzIYLm1y",
            "cGNfYWRtaW4uVGVybWluYWxJbmZvEg0KBWVycm9yGAYgASgJEg8KB2hvc3Rf",
            "aXAYByABKAkSEwoLY3B1X3BlcmNlbnQYCCABKAESEwoLcmFtX3VzZWRfbWIY",
            "CSABKAQSFAoMcmFtX3RvdGFsX21iGAogASgEEi4KDXVzYWdlX2hpc3RvcnkY",
            "CyADKAsyFy5tcnBjX2FkbWluLlVzYWdlU2FtcGxlIkUKG0FjdGl2ZVRlcm1p",
            "bmFsc0NsdXN0ZXJSZXBseRImCgRwb2RzGAEgAygLMhgubXJwY19hZG1pbi5Q",
            "b2RUZXJtaW5hbHMy7QIKCEFkbWluQXBpEnEKD0FjdGl2ZVRlcm1pbmFscxIi",
            "Lm1ycGNfYWRtaW4uQWN0aXZlVGVybWluYWxzUmVxdWVzdBogLm1ycGNfYWRt",
            "aW4uQWN0aXZlVGVybWluYWxzUmVwbHkiGILT5JMCEhIQL0FjdGl2ZVRlcm1p",
            "bmFscxKGAQoWQWN0aXZlVGVybWluYWxzQ2x1c3RlchIiLm1ycGNfYWRtaW4u",
            "QWN0aXZlVGVybWluYWxzUmVxdWVzdBonLm1ycGNfYWRtaW4uQWN0aXZlVGVy",
            "bWluYWxzQ2x1c3RlclJlcGx5Ih+C0+STAhkSFy9BY3RpdmVUZXJtaW5hbHND",
            "bHVzdGVyEmUKC1N5c3RlbVVzYWdlEiIubXJwY19hZG1pbi5BY3RpdmVUZXJt",
            "aW5hbHNSZXF1ZXN0GhwubXJwY19hZG1pbi5TeXN0ZW1Vc2FnZVJlcGx5IhSC",
            "0+STAg4SDC9TeXN0ZW1Vc2FnZUJAWjFnaXQubXRhcGkuaW8vcm9vdC9tcnBj",
            "LXByb3RvLmdpdC9tdDUvbGlicmFyaWVzL2dvqgIKbXJwY19hZG1pbmIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::mrpc_admin.UsageSample), global::mrpc_admin.UsageSample.Parser, new[]{ "Time", "CpuPercent", "RamUsedMb", "RamTotalMb" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::mrpc_admin.SystemUsageReply), global::mrpc_admin.SystemUsageReply.Parser, new[]{ "CpuPercent", "RamUsedMb", "RamTotalMb", "History", "Error" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::mrpc_admin.ActiveTerminalsRequest), global::mrpc_admin.ActiveTerminalsRequest.Parser, new[]{ "AdminKey" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::mrpc_admin.TerminalInfo), global::mrpc_admin.TerminalInfo.Parser, new[]{ "Id", "UserNumber", "WindowsUser", "Account", "Server", "Port", "CreatedAt", "WindowsPassword" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::mrpc_admin.ActiveTerminalsReply), global::mrpc_admin.ActiveTerminalsReply.Parser, new[]{ "Pod", "Node", "PodIp", "Terminals", "Error", "CpuPercent", "RamUsedMb", "RamTotalMb", "UsageHistory" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::mrpc_admin.PodTerminals), global::mrpc_admin.PodTerminals.Parser, new[]{ "Pod", "Node", "PodIp", "NovncUrl", "Terminals", "Error", "HostIp", "CpuPercent", "RamUsedMb", "RamTotalMb", "UsageHistory" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::mrpc_admin.ActiveTerminalsClusterReply), global::mrpc_admin.ActiveTerminalsClusterReply.Parser, new[]{ "Pods" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UsageSample : pb::IMessage<UsageSample>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UsageSample> _parser = new pb::MessageParser<UsageSample>(() => new UsageSample());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UsageSample> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mrpc_admin.Mt5TermApiAdminReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsageSample() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsageSample(UsageSample other) : this() {
      time_ = other.time_ != null ? other.time_.Clone() : null;
      cpuPercent_ = other.cpuPercent_;
      ramUsedMb_ = other.ramUsedMb_;
      ramTotalMb_ = other.ramTotalMb_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsageSample Clone() {
      return new UsageSample(this);
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "cpu_percent" field.</summary>
    public const int CpuPercentFieldNumber = 2;
    private double cpuPercent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double CpuPercent {
      get { return cpuPercent_; }
      set {
        cpuPercent_ = value;
      }
    }

    /// <summary>Field number for the "ram_used_mb" field.</summary>
    public const int RamUsedMbFieldNumber = 3;
    private ulong ramUsedMb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RamUsedMb {
      get { return ramUsedMb_; }
      set {
        ramUsedMb_ = value;
      }
    }

    /// <summary>Field number for the "ram_total_mb" field.</summary>
    public const int RamTotalMbFieldNumber = 4;
    private ulong ramTotalMb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RamTotalMb {
      get { return ramTotalMb_; }
      set {
        ramTotalMb_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UsageSample);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UsageSample other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Time, other.Time)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(CpuPercent, other.CpuPercent)) return false;
      if (RamUsedMb != other.RamUsedMb) return false;
      if (RamTotalMb != other.RamTotalMb) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (time_ != null) hash ^= Time.GetHashCode();
      if (CpuPercent != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(CpuPercent);
      if (RamUsedMb != 0UL) hash ^= RamUsedMb.GetHashCode();
      if (RamTotalMb != 0UL) hash ^= RamTotalMb.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (time_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Time);
      }
      if (CpuPercent != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(CpuPercent);
      }
      if (RamUsedMb != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RamUsedMb);
      }
      if (RamTotalMb != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(RamTotalMb);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (time_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Time);
      }
      if (CpuPercent != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(CpuPercent);
      }
      if (RamUsedMb != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RamUsedMb);
      }
      if (RamTotalMb != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(RamTotalMb);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (time_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
      }
      if (CpuPercent != 0D) {
        size += 1 + 8;
      }
      if (RamUsedMb != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RamUsedMb);
      }
      if (RamTotalMb != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RamTotalMb);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UsageSample other) {
      if (other == null) {
        return;
      }
      if (other.time_ != null) {
        if (time_ == null) {
          Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Time.MergeFrom(other.Time);
      }
      if (other.CpuPercent != 0D) {
        CpuPercent = other.CpuPercent;
      }
      if (other.RamUsedMb != 0UL) {
        RamUsedMb = other.RamUsedMb;
      }
      if (other.RamTotalMb != 0UL) {
        RamTotalMb = other.RamTotalMb;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 17: {
            CpuPercent = input.ReadDouble();
            break;
          }
          case 24: {
            RamUsedMb = input.ReadUInt64();
            break;
          }
          case 32: {
            RamTotalMb = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 17: {
            CpuPercent = input.ReadDouble();
            break;
          }
          case 24: {
            RamUsedMb = input.ReadUInt64();
            break;
          }
          case 32: {
            RamTotalMb = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SystemUsageReply : pb::IMessage<SystemUsageReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SystemUsageReply> _parser = new pb::MessageParser<SystemUsageReply>(() => new SystemUsageReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SystemUsageReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mrpc_admin.Mt5TermApiAdminReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SystemUsageReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SystemUsageReply(SystemUsageReply other) : this() {
      cpuPercent_ = other.cpuPercent_;
      ramUsedMb_ = other.ramUsedMb_;
      ramTotalMb_ = other.ramTotalMb_;
      history_ = other.history_.Clone();
      error_ = other.error_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SystemUsageReply Clone() {
      return new SystemUsageReply(this);
    }

    /// <summary>Field number for the "cpu_percent" field.</summary>
    public const int CpuPercentFieldNumber = 1;
    private double cpuPercent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double CpuPercent {
      get { return cpuPercent_; }
      set {
        cpuPercent_ = value;
      }
    }

    /// <summary>Field number for the "ram_used_mb" field.</summary>
    public const int RamUsedMbFieldNumber = 2;
    private ulong ramUsedMb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RamUsedMb {
      get { return ramUsedMb_; }
      set {
        ramUsedMb_ = value;
      }
    }

    /// <summary>Field number for the "ram_total_mb" field.</summary>
    public const int RamTotalMbFieldNumber = 3;
    private ulong ramTotalMb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RamTotalMb {
      get { return ramTotalMb_; }
      set {
        ramTotalMb_ = value;
      }
    }

    /// <summary>Field number for the "history" field.</summary>
    public const int HistoryFieldNumber = 4;
    private static readonly pb::FieldCodec<global::mrpc_admin.UsageSample> _repeated_history_codec
        = pb::FieldCodec.ForMessage(34, global::mrpc_admin.UsageSample.Parser);
    private readonly pbc::RepeatedField<global::mrpc_admin.UsageSample> history_ = new pbc::RepeatedField<global::mrpc_admin.UsageSample>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::mrpc_admin.UsageSample> History {
      get { return history_; }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 5;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SystemUsageReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SystemUsageReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(CpuPercent, other.CpuPercent)) return false;
      if (RamUsedMb != other.RamUsedMb) return false;
      if (RamTotalMb != other.RamTotalMb) return false;
      if(!history_.Equals(other.history_)) return false;
      if (Error != other.Error) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CpuPercent != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(CpuPercent);
      if (RamUsedMb != 0UL) hash ^= RamUsedMb.GetHashCode();
      if (RamTotalMb != 0UL) hash ^= RamTotalMb.GetHashCode();
      hash ^= history_.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CpuPercent != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(CpuPercent);
      }
      if (RamUsedMb != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(RamUsedMb);
      }
      if (RamTotalMb != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RamTotalMb);
      }
      history_.WriteTo(output, _repeated_history_codec);
      if (Error.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CpuPercent != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(CpuPercent);
      }
      if (RamUsedMb != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(RamUsedMb);
      }
      if (RamTotalMb != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RamTotalMb);
      }
      history_.WriteTo(ref output, _repeated_history_codec);
      if (Error.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CpuPercent != 0D) {
        size += 1 + 8;
      }
      if (RamUsedMb != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RamUsedMb);
      }
      if (RamTotalMb != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RamTotalMb);
      }
      size += history_.CalculateSize(_repeated_history_codec);
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SystemUsageReply other) {
      if (other == null) {
        return;
      }
      if (other.CpuPercent != 0D) {
        CpuPercent = other.CpuPercent;
      }
      if (other.RamUsedMb != 0UL) {
        RamUsedMb = other.RamUsedMb;
      }
      if (other.RamTotalMb != 0UL) {
        RamTotalMb = other.RamTotalMb;
      }
      history_.Add(other.history_);
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            CpuPercent = input.ReadDouble();
            break;
          }
          case 16: {
            RamUsedMb = input.ReadUInt64();
            break;
          }
          case 24: {
            RamTotalMb = input.ReadUInt64();
            break;
          }
          case 34: {
            history_.AddEntriesFrom(input, _repeated_history_codec);
            break;
          }
          case 42: {
            Error = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            CpuPercent = input.ReadDouble();
            break;
          }
          case 16: {
            RamUsedMb = input.ReadUInt64();
            break;
          }
          case 24: {
            RamTotalMb = input.ReadUInt64();
            break;
          }
          case 34: {
            history_.AddEntriesFrom(ref input, _repeated_history_codec);
            break;
          }
          case 42: {
            Error = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ActiveTerminalsRequest : pb::IMessage<ActiveTerminalsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActiveTerminalsRequest> _parser = new pb::MessageParser<ActiveTerminalsRequest>(() => new ActiveTerminalsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActiveTerminalsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mrpc_admin.Mt5TermApiAdminReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActiveTerminalsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActiveTerminalsRequest(ActiveTerminalsRequest other) : this() {
      adminKey_ = other.adminKey_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActiveTerminalsRequest Clone() {
      return new ActiveTerminalsRequest(this);
    }

    /// <summary>Field number for the "admin_key" field.</summary>
    public const int AdminKeyFieldNumber = 1;
    private string adminKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AdminKey {
      get { return adminKey_; }
      set {
        adminKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActiveTerminalsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActiveTerminalsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AdminKey != other.AdminKey) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AdminKey.Length != 0) hash ^= AdminKey.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AdminKey.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AdminKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AdminKey.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AdminKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AdminKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AdminKey);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActiveTerminalsRequest other) {
      if (other == null) {
        return;
      }
      if (other.AdminKey.Length != 0) {
        AdminKey = other.AdminKey;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AdminKey = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AdminKey = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TerminalInfo : pb::IMessage<TerminalInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TerminalInfo> _parser = new pb::MessageParser<TerminalInfo>(() => new TerminalInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TerminalInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mrpc_admin.Mt5TermApiAdminReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TerminalInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TerminalInfo(TerminalInfo other) : this() {
      id_ = other.id_;
      userNumber_ = other.userNumber_;
      windowsUser_ = other.windowsUser_;
      account_ = other.account_;
      server_ = other.server_;
      port_ = other.port_;
      createdAt_ = other.createdAt_ != null ? other.createdAt_.Clone() : null;
      windowsPassword_ = other.windowsPassword_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TerminalInfo Clone() {
      return new TerminalInfo(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    /// <summary>
    /// terminal instance GUID (the `id` header)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_number" field.</summary>
    public const int UserNumberFieldNumber = 2;
    private uint userNumber_;
    /// <summary>
    /// MrpcTerminalUser&lt;N>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UserNumber {
      get { return userNumber_; }
      set {
        userNumber_ = value;
      }
    }

    /// <summary>Field number for the "windows_user" field.</summary>
    public const int WindowsUserFieldNumber = 3;
    private string windowsUser_ = "";
    /// <summary>
    /// e.g. "MrpcTerminalUser3"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WindowsUser {
      get { return windowsUser_; }
      set {
        windowsUser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 4;
    private ulong account_;
    /// <summary>
    /// MT login
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Account {
      get { return account_; }
      set {
        account_ = value;
      }
    }

    /// <summary>Field number for the "server" field.</summary>
    public const int ServerFieldNumber = 5;
    private string server_ = "";
    /// <summary>
    /// broker / MT cluster name
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Server {
      get { return server_; }
      set {
        server_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 6;
    private uint port_;
    /// <summary>
    /// terminal api port
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createdAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    /// <summary>Field number for the "windows_password" field.</summary>
    public const int WindowsPasswordFieldNumber = 8;
    private string windowsPassword_ = "";
    /// <summary>
    /// RDP password for windows_user (admin-only)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WindowsPassword {
      get { return windowsPassword_; }
      set {
        windowsPassword_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TerminalInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TerminalInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (UserNumber != other.UserNumber) return false;
      if (WindowsUser != other.WindowsUser) return false;
      if (Account != other.Account) return false;
      if (Server != other.Server) return false;
      if (Port != other.Port) return false;
      if (!object.Equals(CreatedAt, other.CreatedAt)) return false;
      if (WindowsPassword != other.WindowsPassword) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (UserNumber != 0) hash ^= UserNumber.GetHashCode();
      if (WindowsUser.Length != 0) hash ^= WindowsUser.GetHashCode();
      if (Account != 0UL) hash ^= Account.GetHashCode();
      if (Server.Length != 0) hash ^= Server.GetHashCode();
      if (Port != 0) hash ^= Port.GetHashCode();
      if (createdAt_ != null) hash ^= CreatedAt.GetHashCode();
      if (WindowsPassword.Length != 0) hash ^= WindowsPassword.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (UserNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(UserNumber);
      }
      if (WindowsUser.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(WindowsUser);
      }
      if (Account != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(Account);
      }
      if (Server.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Server);
      }
      if (Port != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Port);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CreatedAt);
      }
      if (WindowsPassword.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(WindowsPassword);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (UserNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(UserNumber);
      }
      if (WindowsUser.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(WindowsUser);
      }
      if (Account != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(Account);
      }
      if (Server.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Server);
      }
      if (Port != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Port);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CreatedAt);
      }
      if (WindowsPassword.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(WindowsPassword);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (UserNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UserNumber);
      }
      if (WindowsUser.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WindowsUser);
      }
      if (Account != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Account);
      }
      if (Server.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Server);
      }
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Port);
      }
      if (createdAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedAt);
      }
      if (WindowsPassword.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WindowsPassword);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TerminalInfo other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.UserNumber != 0) {
        UserNumber = other.UserNumber;
      }
      if (other.WindowsUser.Length != 0) {
        WindowsUser = other.WindowsUser;
      }
      if (other.Account != 0UL) {
        Account = other.Account;
      }
      if (other.Server.Length != 0) {
        Server = other.Server;
      }
      if (other.Port != 0) {
        Port = other.Port;
      }
      if (other.createdAt_ != null) {
        if (createdAt_ == null) {
          CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreatedAt.MergeFrom(other.CreatedAt);
      }
      if (other.WindowsPassword.Length != 0) {
        WindowsPassword = other.WindowsPassword;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            UserNumber = input.ReadUInt32();
            break;
          }
          case 26: {
            WindowsUser = input.ReadString();
            break;
          }
          case 32: {
            Account = input.ReadUInt64();
            break;
          }
          case 42: {
            Server = input.ReadString();
            break;
          }
          case 48: {
            Port = input.ReadUInt32();
            break;
          }
          case 58: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 66: {
            WindowsPassword = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            UserNumber = input.ReadUInt32();
            break;
          }
          case 26: {
            WindowsUser = input.ReadString();
            break;
          }
          case 32: {
            Account = input.ReadUInt64();
            break;
          }
          case 42: {
            Server = input.ReadString();
            break;
          }
          case 48: {
            Port = input.ReadUInt32();
            break;
          }
          case 58: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 66: {
            WindowsPassword = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ActiveTerminalsReply : pb::IMessage<ActiveTerminalsReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActiveTerminalsReply> _parser = new pb::MessageParser<ActiveTerminalsReply>(() => new ActiveTerminalsReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActiveTerminalsReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mrpc_admin.Mt5TermApiAdminReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActiveTerminalsReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActiveTerminalsReply(ActiveTerminalsReply other) : this() {
      pod_ = other.pod_;
      node_ = other.node_;
      podIp_ = other.podIp_;
      terminals_ = other.terminals_.Clone();
      error_ = other.error_;
      cpuPercent_ = other.cpuPercent_;
      ramUsedMb_ = other.ramUsedMb_;
      ramTotalMb_ = other.ramTotalMb_;
      usageHistory_ = other.usageHistory_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActiveTerminalsReply Clone() {
      return new ActiveTerminalsReply(this);
    }

    /// <summary>Field number for the "pod" field.</summary>
    public const int PodFieldNumber = 1;
    private string pod_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Pod {
      get { return pod_; }
      set {
        pod_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "node" field.</summary>
    public const int NodeFieldNumber = 2;
    private string node_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Node {
      get { return node_; }
      set {
        node_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pod_ip" field.</summary>
    public const int PodIpFieldNumber = 3;
    private string podIp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PodIp {
      get { return podIp_; }
      set {
        podIp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "terminals" field.</summary>
    public const int TerminalsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::mrpc_admin.TerminalInfo> _repeated_terminals_codec
        = pb::FieldCodec.ForMessage(34, global::mrpc_admin.TerminalInfo.Parser);
    private readonly pbc::RepeatedField<global::mrpc_admin.TerminalInfo> terminals_ = new pbc::RepeatedField<global::mrpc_admin.TerminalInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::mrpc_admin.TerminalInfo> Terminals {
      get { return terminals_; }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 5;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cpu_percent" field.</summary>
    public const int CpuPercentFieldNumber = 6;
    private double cpuPercent_;
    /// <summary>
    /// whole-machine CPU % for this pod
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double CpuPercent {
      get { return cpuPercent_; }
      set {
        cpuPercent_ = value;
      }
    }

    /// <summary>Field number for the "ram_used_mb" field.</summary>
    public const int RamUsedMbFieldNumber = 7;
    private ulong ramUsedMb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RamUsedMb {
      get { return ramUsedMb_; }
      set {
        ramUsedMb_ = value;
      }
    }

    /// <summary>Field number for the "ram_total_mb" field.</summary>
    public const int RamTotalMbFieldNumber = 8;
    private ulong ramTotalMb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RamTotalMb {
      get { return ramTotalMb_; }
      set {
        ramTotalMb_ = value;
      }
    }

    /// <summary>Field number for the "usage_history" field.</summary>
    public const int UsageHistoryFieldNumber = 9;
    private static readonly pb::FieldCodec<global::mrpc_admin.UsageSample> _repeated_usageHistory_codec
        = pb::FieldCodec.ForMessage(74, global::mrpc_admin.UsageSample.Parser);
    private readonly pbc::RepeatedField<global::mrpc_admin.UsageSample> usageHistory_ = new pbc::RepeatedField<global::mrpc_admin.UsageSample>();
    /// <summary>
    /// short CPU/RAM history
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::mrpc_admin.UsageSample> UsageHistory {
      get { return usageHistory_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActiveTerminalsReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActiveTerminalsReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Pod != other.Pod) return false;
      if (Node != other.Node) return false;
      if (PodIp != other.PodIp) return false;
      if(!terminals_.Equals(other.terminals_)) return false;
      if (Error != other.Error) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(CpuPercent, other.CpuPercent)) return false;
      if (RamUsedMb != other.RamUsedMb) return false;
      if (RamTotalMb != other.RamTotalMb) return false;
      if(!usageHistory_.Equals(other.usageHistory_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Pod.Length != 0) hash ^= Pod.GetHashCode();
      if (Node.Length != 0) hash ^= Node.GetHashCode();
      if (PodIp.Length != 0) hash ^= PodIp.GetHashCode();
      hash ^= terminals_.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (CpuPercent != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(CpuPercent);
      if (RamUsedMb != 0UL) hash ^= RamUsedMb.GetHashCode();
      if (RamTotalMb != 0UL) hash ^= RamTotalMb.GetHashCode();
      hash ^= usageHistory_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Pod.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Pod);
      }
      if (Node.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Node);
      }
      if (PodIp.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PodIp);
      }
      terminals_.WriteTo(output, _repeated_terminals_codec);
      if (Error.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Error);
      }
      if (CpuPercent != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(CpuPercent);
      }
      if (RamUsedMb != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(RamUsedMb);
      }
      if (RamTotalMb != 0UL) {
        output.WriteRawTag(64);
        output.WriteUInt64(RamTotalMb);
      }
      usageHistory_.WriteTo(output, _repeated_usageHistory_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Pod.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Pod);
      }
      if (Node.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Node);
      }
      if (PodIp.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PodIp);
      }
      terminals_.WriteTo(ref output, _repeated_terminals_codec);
      if (Error.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Error);
      }
      if (CpuPercent != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(CpuPercent);
      }
      if (RamUsedMb != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(RamUsedMb);
      }
      if (RamTotalMb != 0UL) {
        output.WriteRawTag(64);
        output.WriteUInt64(RamTotalMb);
      }
      usageHistory_.WriteTo(ref output, _repeated_usageHistory_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Pod.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Pod);
      }
      if (Node.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Node);
      }
      if (PodIp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PodIp);
      }
      size += terminals_.CalculateSize(_repeated_terminals_codec);
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (CpuPercent != 0D) {
        size += 1 + 8;
      }
      if (RamUsedMb != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RamUsedMb);
      }
      if (RamTotalMb != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RamTotalMb);
      }
      size += usageHistory_.CalculateSize(_repeated_usageHistory_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActiveTerminalsReply other) {
      if (other == null) {
        return;
      }
      if (other.Pod.Length != 0) {
        Pod = other.Pod;
      }
      if (other.Node.Length != 0) {
        Node = other.Node;
      }
      if (other.PodIp.Length != 0) {
        PodIp = other.PodIp;
      }
      terminals_.Add(other.terminals_);
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.CpuPercent != 0D) {
        CpuPercent = other.CpuPercent;
      }
      if (other.RamUsedMb != 0UL) {
        RamUsedMb = other.RamUsedMb;
      }
      if (other.RamTotalMb != 0UL) {
        RamTotalMb = other.RamTotalMb;
      }
      usageHistory_.Add(other.usageHistory_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Pod = input.ReadString();
            break;
          }
          case 18: {
            Node = input.ReadString();
            break;
          }
          case 26: {
            PodIp = input.ReadString();
            break;
          }
          case 34: {
            terminals_.AddEntriesFrom(input, _repeated_terminals_codec);
            break;
          }
          case 42: {
            Error = input.ReadString();
            break;
          }
          case 49: {
            CpuPercent = input.ReadDouble();
            break;
          }
          case 56: {
            RamUsedMb = input.ReadUInt64();
            break;
          }
          case 64: {
            RamTotalMb = input.ReadUInt64();
            break;
          }
          case 74: {
            usageHistory_.AddEntriesFrom(input, _repeated_usageHistory_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Pod = input.ReadString();
            break;
          }
          case 18: {
            Node = input.ReadString();
            break;
          }
          case 26: {
            PodIp = input.ReadString();
            break;
          }
          case 34: {
            terminals_.AddEntriesFrom(ref input, _repeated_terminals_codec);
            break;
          }
          case 42: {
            Error = input.ReadString();
            break;
          }
          case 49: {
            CpuPercent = input.ReadDouble();
            break;
          }
          case 56: {
            RamUsedMb = input.ReadUInt64();
            break;
          }
          case 64: {
            RamTotalMb = input.ReadUInt64();
            break;
          }
          case 74: {
            usageHistory_.AddEntriesFrom(ref input, _repeated_usageHistory_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PodTerminals : pb::IMessage<PodTerminals>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PodTerminals> _parser = new pb::MessageParser<PodTerminals>(() => new PodTerminals());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PodTerminals> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mrpc_admin.Mt5TermApiAdminReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PodTerminals() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PodTerminals(PodTerminals other) : this() {
      pod_ = other.pod_;
      node_ = other.node_;
      podIp_ = other.podIp_;
      novncUrl_ = other.novncUrl_;
      terminals_ = other.terminals_.Clone();
      error_ = other.error_;
      hostIp_ = other.hostIp_;
      cpuPercent_ = other.cpuPercent_;
      ramUsedMb_ = other.ramUsedMb_;
      ramTotalMb_ = other.ramTotalMb_;
      usageHistory_ = other.usageHistory_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PodTerminals Clone() {
      return new PodTerminals(this);
    }

    /// <summary>Field number for the "pod" field.</summary>
    public const int PodFieldNumber = 1;
    private string pod_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Pod {
      get { return pod_; }
      set {
        pod_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "node" field.</summary>
    public const int NodeFieldNumber = 2;
    private string node_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Node {
      get { return node_; }
      set {
        node_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pod_ip" field.</summary>
    public const int PodIpFieldNumber = 3;
    private string podIp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PodIp {
      get { return podIp_; }
      set {
        podIp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "novnc_url" field.</summary>
    public const int NovncUrlFieldNumber = 4;
    private string novncUrl_ = "";
    /// <summary>
    /// link to the pod's noVNC viewer
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NovncUrl {
      get { return novncUrl_; }
      set {
        novncUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "terminals" field.</summary>
    public const int TerminalsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::mrpc_admin.TerminalInfo> _repeated_terminals_codec
        = pb::FieldCodec.ForMessage(42, global::mrpc_admin.TerminalInfo.Parser);
    private readonly pbc::RepeatedField<global::mrpc_admin.TerminalInfo> terminals_ = new pbc::RepeatedField<global::mrpc_admin.TerminalInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::mrpc_admin.TerminalInfo> Terminals {
      get { return terminals_; }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 6;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "host_ip" field.</summary>
    public const int HostIpFieldNumber = 7;
    private string hostIp_ = "";
    /// <summary>
    /// node IP (for the RDP NodePort target)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string HostIp {
      get { return hostIp_; }
      set {
        hostIp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cpu_percent" field.</summary>
    public const int CpuPercentFieldNumber = 8;
    private double cpuPercent_;
    /// <summary>
    /// whole-machine CPU % for this pod
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double CpuPercent {
      get { return cpuPercent_; }
      set {
        cpuPercent_ = value;
      }
    }

    /// <summary>Field number for the "ram_used_mb" field.</summary>
    public const int RamUsedMbFieldNumber = 9;
    private ulong ramUsedMb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RamUsedMb {
      get { return ramUsedMb_; }
      set {
        ramUsedMb_ = value;
      }
    }

    /// <summary>Field number for the "ram_total_mb" field.</summary>
    public const int RamTotalMbFieldNumber = 10;
    private ulong ramTotalMb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RamTotalMb {
      get { return ramTotalMb_; }
      set {
        ramTotalMb_ = value;
      }
    }

    /// <summary>Field number for the "usage_history" field.</summary>
    public const int UsageHistoryFieldNumber = 11;
    private static readonly pb::FieldCodec<global::mrpc_admin.UsageSample> _repeated_usageHistory_codec
        = pb::FieldCodec.ForMessage(90, global::mrpc_admin.UsageSample.Parser);
    private readonly pbc::RepeatedField<global::mrpc_admin.UsageSample> usageHistory_ = new pbc::RepeatedField<global::mrpc_admin.UsageSample>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::mrpc_admin.UsageSample> UsageHistory {
      get { return usageHistory_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PodTerminals);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PodTerminals other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Pod != other.Pod) return false;
      if (Node != other.Node) return false;
      if (PodIp != other.PodIp) return false;
      if (NovncUrl != other.NovncUrl) return false;
      if(!terminals_.Equals(other.terminals_)) return false;
      if (Error != other.Error) return false;
      if (HostIp != other.HostIp) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(CpuPercent, other.CpuPercent)) return false;
      if (RamUsedMb != other.RamUsedMb) return false;
      if (RamTotalMb != other.RamTotalMb) return false;
      if(!usageHistory_.Equals(other.usageHistory_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Pod.Length != 0) hash ^= Pod.GetHashCode();
      if (Node.Length != 0) hash ^= Node.GetHashCode();
      if (PodIp.Length != 0) hash ^= PodIp.GetHashCode();
      if (NovncUrl.Length != 0) hash ^= NovncUrl.GetHashCode();
      hash ^= terminals_.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (HostIp.Length != 0) hash ^= HostIp.GetHashCode();
      if (CpuPercent != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(CpuPercent);
      if (RamUsedMb != 0UL) hash ^= RamUsedMb.GetHashCode();
      if (RamTotalMb != 0UL) hash ^= RamTotalMb.GetHashCode();
      hash ^= usageHistory_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Pod.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Pod);
      }
      if (Node.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Node);
      }
      if (PodIp.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PodIp);
      }
      if (NovncUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NovncUrl);
      }
      terminals_.WriteTo(output, _repeated_terminals_codec);
      if (Error.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Error);
      }
      if (HostIp.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(HostIp);
      }
      if (CpuPercent != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(CpuPercent);
      }
      if (RamUsedMb != 0UL) {
        output.WriteRawTag(72);
        output.WriteUInt64(RamUsedMb);
      }
      if (RamTotalMb != 0UL) {
        output.WriteRawTag(80);
        output.WriteUInt64(RamTotalMb);
      }
      usageHistory_.WriteTo(output, _repeated_usageHistory_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Pod.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Pod);
      }
      if (Node.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Node);
      }
      if (PodIp.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PodIp);
      }
      if (NovncUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NovncUrl);
      }
      terminals_.WriteTo(ref output, _repeated_terminals_codec);
      if (Error.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Error);
      }
      if (HostIp.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(HostIp);
      }
      if (CpuPercent != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(CpuPercent);
      }
      if (RamUsedMb != 0UL) {
        output.WriteRawTag(72);
        output.WriteUInt64(RamUsedMb);
      }
      if (RamTotalMb != 0UL) {
        output.WriteRawTag(80);
        output.WriteUInt64(RamTotalMb);
      }
      usageHistory_.WriteTo(ref output, _repeated_usageHistory_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Pod.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Pod);
      }
      if (Node.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Node);
      }
      if (PodIp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PodIp);
      }
      if (NovncUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NovncUrl);
      }
      size += terminals_.CalculateSize(_repeated_terminals_codec);
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (HostIp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HostIp);
      }
      if (CpuPercent != 0D) {
        size += 1 + 8;
      }
      if (RamUsedMb != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RamUsedMb);
      }
      if (RamTotalMb != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RamTotalMb);
      }
      size += usageHistory_.CalculateSize(_repeated_usageHistory_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PodTerminals other) {
      if (other == null) {
        return;
      }
      if (other.Pod.Length != 0) {
        Pod = other.Pod;
      }
      if (other.Node.Length != 0) {
        Node = other.Node;
      }
      if (other.PodIp.Length != 0) {
        PodIp = other.PodIp;
      }
      if (other.NovncUrl.Length != 0) {
        NovncUrl = other.NovncUrl;
      }
      terminals_.Add(other.terminals_);
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.HostIp.Length != 0) {
        HostIp = other.HostIp;
      }
      if (other.CpuPercent != 0D) {
        CpuPercent = other.CpuPercent;
      }
      if (other.RamUsedMb != 0UL) {
        RamUsedMb = other.RamUsedMb;
      }
      if (other.RamTotalMb != 0UL) {
        RamTotalMb = other.RamTotalMb;
      }
      usageHistory_.Add(other.usageHistory_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Pod = input.ReadString();
            break;
          }
          case 18: {
            Node = input.ReadString();
            break;
          }
          case 26: {
            PodIp = input.ReadString();
            break;
          }
          case 34: {
            NovncUrl = input.ReadString();
            break;
          }
          case 42: {
            terminals_.AddEntriesFrom(input, _repeated_terminals_codec);
            break;
          }
          case 50: {
            Error = input.ReadString();
            break;
          }
          case 58: {
            HostIp = input.ReadString();
            break;
          }
          case 65: {
            CpuPercent = input.ReadDouble();
            break;
          }
          case 72: {
            RamUsedMb = input.ReadUInt64();
            break;
          }
          case 80: {
            RamTotalMb = input.ReadUInt64();
            break;
          }
          case 90: {
            usageHistory_.AddEntriesFrom(input, _repeated_usageHistory_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Pod = input.ReadString();
            break;
          }
          case 18: {
            Node = input.ReadString();
            break;
          }
          case 26: {
            PodIp = input.ReadString();
            break;
          }
          case 34: {
            NovncUrl = input.ReadString();
            break;
          }
          case 42: {
            terminals_.AddEntriesFrom(ref input, _repeated_terminals_codec);
            break;
          }
          case 50: {
            Error = input.ReadString();
            break;
          }
          case 58: {
            HostIp = input.ReadString();
            break;
          }
          case 65: {
            CpuPercent = input.ReadDouble();
            break;
          }
          case 72: {
            RamUsedMb = input.ReadUInt64();
            break;
          }
          case 80: {
            RamTotalMb = input.ReadUInt64();
            break;
          }
          case 90: {
            usageHistory_.AddEntriesFrom(ref input, _repeated_usageHistory_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ActiveTerminalsClusterReply : pb::IMessage<ActiveTerminalsClusterReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActiveTerminalsClusterReply> _parser = new pb::MessageParser<ActiveTerminalsClusterReply>(() => new ActiveTerminalsClusterReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActiveTerminalsClusterReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mrpc_admin.Mt5TermApiAdminReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActiveTerminalsClusterReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActiveTerminalsClusterReply(ActiveTerminalsClusterReply other) : this() {
      pods_ = other.pods_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActiveTerminalsClusterReply Clone() {
      return new ActiveTerminalsClusterReply(this);
    }

    /// <summary>Field number for the "pods" field.</summary>
    public const int PodsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::mrpc_admin.PodTerminals> _repeated_pods_codec
        = pb::FieldCodec.ForMessage(10, global::mrpc_admin.PodTerminals.Parser);
    private readonly pbc::RepeatedField<global::mrpc_admin.PodTerminals> pods_ = new pbc::RepeatedField<global::mrpc_admin.PodTerminals>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::mrpc_admin.PodTerminals> Pods {
      get { return pods_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActiveTerminalsClusterReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActiveTerminalsClusterReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!pods_.Equals(other.pods_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= pods_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      pods_.WriteTo(output, _repeated_pods_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      pods_.WriteTo(ref output, _repeated_pods_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += pods_.CalculateSize(_repeated_pods_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActiveTerminalsClusterReply other) {
      if (other == null) {
        return;
      }
      pods_.Add(other.pods_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            pods_.AddEntriesFrom(input, _repeated_pods_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            pods_.AddEntriesFrom(ref input, _repeated_pods_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
